### ISSUE TITLE
ADD more "covid_test_types" in patient card creation form

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#1860]
Currently, In "Covid_test_type" field in Patient card creation form, there is  RT-PCR, TRUENAT, CBNAAT, ANTIGEN present in the dropdown. add two more test type to the dropdown for the same.

what to add;

1) RT-LAMP
2) POC-PCR

**Comment by Sandra3657** [comment]
@samholics. The covid test type should displayed in the sample test details also, right? Currently, its always displaying only '-' for any test type.

![image](https://user-images.githubusercontent.com/62461536/134936392-7c982c8d-d48b-472a-824a-7a279013a078.png)

**Comment by Apurva-Nagar** [comment]
Related Backend PR - https://github.com/coronasafe/care/pull/626

**Comment by samholics** [comment]
@Sandra3657  no    "Covid_test_type" only applicable when creating a new patient card. Its not the same in Sample test management.
 In  sample test management its "sample_test_type" its different.

**Comment by Sandra3657** [comment]
Ok. But when I fix the minor issue (test type is always showing "-"),  this is being displayed. So, the code needs to be modified to display "sample test type" instead of "covid test type"? @samholics 
![image](https://user-images.githubusercontent.com/62461536/135021242-9a0c9aa7-70b6-4c2c-be4c-3a21465bb9de.png)

**Comment by samholics** [comment]
@Sandra3657  refer PR #1834, if anything comes up pls ping me.

**Comment by Sandra3657** [comment]
Ok. got it
