### ISSUE TITLE
Hub Camera Monitoring Screen

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#2091]
**Describe the bug**  Modified on 19/05/2023

Currently, on the platform, we do not have a page similar to the Central CNS page where we can view all the camera feed inside a facility at once.

**Steps to view the central CNS page**

1. go to https://care.coronasafe.in/ and log in with the credentials in the readme
2. Search for the name of the "Critical Care" facility and click on the CNS button.
3. The Page you are viewing is the central view with show vital monitors of all patient inside the facility

**Expected Solution**

Create a Screen that can View multiple Live Camera Feeds

- [ ] Work on the LiveFeedTile Component, Make it a simple Tile (Optional: Hovering on it the presets can show up.)
- [ ] Create a local storage that can store a set of asset_id for the specific hub device
- [ ] List the list of asset_ids as LiveFeedTiles as the Hub View
- [ ] More UX tweaks to Open the right Patient from the Hub (Wishlist)

**Comment by gigincg** [comment]
Here's a design Reference for What the LiveFeed Hub View would look like

![image](https://user-images.githubusercontent.com/13028584/153694538-3de6cff4-13ff-4025-b434-c76ed9bf5a7b.png)

**Comment by aparnacoronasafe** [comment]
The Tab may be called "Live Monitoring"

Let's have a list of various hospitals on top like the various tabs on the patient dashboard for "Update", "Summary", "medicines, etc. as the user clicks on various tabs, all cameras from the hospital must show up.

The Feed must show the bed no. its looking at. the default view must be a "Patient view" for any bed. 

Ideally, the camera must be programmed to keep moving from one bed to another. But since our ratio of cameras to bed is low (2 or 3 :10), and we need to prioritize doctors trying to view individual patient records through the patient dashboard. the camera being controlled through the patient dashboard must show (on the monitoring screen) that its being used. So that the person using this monitoring screen will know that the camera is being controlled by a doctor. 

Ideally, The monitoring screen must also have some controls, to pause or go back. But I dont know how complex executing is smoothly would be. @gigincg please comment

**Comment by aparnacoronasafe** [comment]
@rabilrbl We need to discuss a few issues before you go ahead with this. I am afraid if we deploy this, multiple users will be trying to control the camera which might cause chaos. 

Please join EOD and discuss this

**Comment by nihal467** [comment]
This issue was modified on 19/05/2023, and it is now ready to be taken by the developers.

**Comment by kshitijv256** [comment]
Please assign me this issue
