### ISSUE TITLE
Review Alert : Broken

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#2587]
The review alert feature is malfunctioning. 

A review missed tag is appearing on the patient card, even when the user does not set any review alerts.

Ideal behavior of review alerts:
- The user must be able to enable a review alert at any set time either in the Consultation form (https://care.coronasafe.in/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8/consultation/d794ba54-da42-4238-8ba9-0b628ca60069/update) or the Log Update Form (https://care.coronasafe.in/facility/7a560e62-6aae-4293-8f1a-0ba840e3449f/patient/192fdee9-397f-49bd-833a-10f700416da8/consultation/d794ba54-da42-4238-8ba9-0b628ca60069/daily-rounds/06312fa0-0b97-4cf6-bf76-8cd990c4f461/update)
- Only when the user has added review time, and no log update is saved within that timeframe, then a "Review Missed" flag must appear on the patient card.
- When a log Update is filed subsequently for the patient, the "Review Missed" flag must disappear. 
- When a new log update is filed, any review set in the previous log updates/consultation must be auto-filled in the new log update form
- The "Review Missed" flag must disappear when the patient is discharged. 

@vigneshhari @bodhish @gigincg

**Comment by nihal467** [comment]
@Ashesh3 

![image](https://user-images.githubusercontent.com/57055998/223137861-39db3d76-5a9c-4b14-b3c7-ac1bc9dc2b2f.png)

The review time feature was taken down due to lots of bugs, currently, in the platform, we are only able to select the review time in the log update and submit it. but, it is not getting reflected anywhere on the platform. so, we need to fix the feature to its ideal behavior.

**Comment by nihal467** [comment]
the issue is resolved
