### ISSUE TITLE
Upload Patient File: Malfunction

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#2985]
![4](https://user-images.githubusercontent.com/57055998/177028117-219ff32b-65c5-4f90-a1e7-d7f048306dcb.jpg)

- [ ] unable to download a lengthy audio file
- [ ] add a timer during the recording time, so the user can understand, the length of audio during record

**Comment by patelaryan7751** [comment]
@nihal467 can you specify how long recording audio the problem is coming. I recorded a long video of 37 secs I refreshed the page when I viewed it the download option was not there but when I listened to it for 37 sec the download option came back so what should be done?
![image](https://user-images.githubusercontent.com/59426397/177028963-bc1b9a0e-b489-46f3-b563-a01a415663b8.png)
This indicates after listening to the audio the download option is coming.

**Comment by gigincg** [comment]
@patelaryan7751 Seems like it's available only after it's entirely fetched

Maybe we can have a separate download button

**Comment by patelaryan7751** [comment]
@gigincg yeah we can do that . Working on it.
