### ISSUE TITLE
Unable to Preview old files

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3073]
![16](https://user-images.githubusercontent.com/57055998/178096331-40b2f516-7b69-4b69-ac02-6811fe1d7d5b.jpg)

the preview is failing for old documents in care

https://care.coronasafe.in/facility/bd466cf6-0fde-46b1-9591-0acf9d955dd1/patient/8027c51f-f6bf-449f-81a2-1c1fba999ac0/consultation/bc7dd32d-7840-420c-a23c-07f5d3727de9/files

**Comment by aeswibon** [comment]
@nihal467 File uploading wasn't working correctly before. As per this [comment](https://github.com/coronasafe/care_fe/issues/2297#issuecomment-1154171377), this issue was solved on 13th June. Before that date, even though a new entry was created, no assets were saved in Amazon Bucket. So your 11th June entry shows no asset.
