### ISSUE TITLE
Move "Health Details" and "Medical History" from patient registration form to consultation form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#3331]
Move the "Health Details" and "Medical History"
From 
patient registration form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/update)
to 
Consultation Form (https://care.coronasafe.in/facility/cae151a7-1b0d-4d76-9d61-a2733b65c648/patient/69b26ab0-a158-414f-950a-f033ea859e51/consultation)

-The sections must come on top as collapsable sections
- The sections must come expanded only in the first consultation on a patient card in care. For all subsequent consultations, the sections must be minimized and only the header must be visible, with the option to expand.
- The sections will be blank only for the first consultation for a patient in care. For every subsequent consultation, the sections must come prefilled with previous consultation data. The user must be able to edit and save.
- The existing content in the consultation form will come under the section heading "consultation"
- "Medical History" to appear on top, then "Health Details" and last place the "Consultation"
- A suggestive design is as under (DONOT follow the design for details. Follow the existing styling, fonts etc in CARE)
<img width="530" alt="Screenshot 2022-08-05 at 9 42 01 PM" src="https://user-images.githubusercontent.com/67050716/183118699-2715dbc3-2868-4673-b562-f9907e9a6a85.png">

@gigincg Please review
Part of #2218

**Comment by gigincg** [comment]
@aparnacoronasafe Since we'll be keeping Public Health Details (Or COVID Details) In Patient Registration. Can we summarise the changes needed to the following

In Consultation:
 - Create "Health Details" Collapsible Section
 - Add Allergies to Health Details
 - Add Blood Group to Health Details
 - Move Height & Weight to Health Details
 - Add Family History to Health Details
 - Add Complete Medical History Section from Patient Registration, except for "Blood Group"

Meanwhile in the Patient Registration Form:
 - Remove Blood Group
 - Remove Medical History Section.
 - Rename Health Details Section to Public Health Details

**Comment by aparnacoronasafe** [comment]
@gigincg  Preserving the COVID Specific details, made edits to #3341 

I have further broken down the issues to have each of the points above as one separate issue. Since for many fields, more details have to be added in, I thought its best to break things down.

**Comment by aparnacoronasafe** [comment]
A quick clarification on the content of the Patient registration form and consultation form
<img width="932" alt="Screenshot 2022-08-12 at 5 22 32 PM" src="https://user-images.githubusercontent.com/67050716/184351271-1a9feb50-2550-43f0-a4b0-491af4f2349a.png">

**Comment by gigincg** [comment]
Additional Context for Medical History & Health Details.

During the first consultation (When `patient.last_consultation` is null) The accordions should be expanded by default. Otherwise, they would be collapsed by default.

There should be 2 new fields to patient_consultation
 - health_details_updated_on
 - medical_history_updated_on

Medical History & Health Details would be non-editable by default.

There would be an edit button for each. onClick of the Edit Button, the updated_on for the respective field would be set to the current date.

The backend should validate if the updated_on is valid

cc: @vigneshhari

**Comment by nihal467** [comment]
@aparnacoronasafe do check this and comment on it

**Comment by nihal467** [comment]
@cp-Coder Due to inactivity and the existing linked PR is not mergeable, unlinking you from this issue

As per the communication with @aparnacoronasafe , it will be sub-grouped with events module, so for time-being marking the issue as blocked

**Comment by aparnacoronasafe** [comment]
Issue updated in #7815 
Closing as redundant
