### ISSUE TITLE
Facility search dropdown in patients tab not visible completely

### ISSUE THREAD

**Issue by GokulramGHV** [coronasafe/care_fe#3841]
**Describe the bug**
The search for facility dropdown is not fully visible.

**To Reproduce**

1. Go to https://care.coronasafe.in/patients
2. Click on 'Add Details of a Patient'
3. The facility search modal pops up and try entering few characters

**Expected behavior**
The dropdown must be visible completely

**Screenshots**
![chrome_vWKEpvLP7c](https://user-images.githubusercontent.com/40627011/198421990-8b5c4430-c971-4747-bfa8-2d1ea8e46193.gif)

**Comment by nihal467** [comment]
@GokulramGHV work on this ASAP

**Comment by nihal467** [comment]
@GokulramGHV what is the status on this issue

**Comment by khavinshankar** [comment]
@GokulramGHV I have taken care of this issue as this was an urgent one, feel free to pick up other issue or you can work on the follow-up for this issue

The fix for this issue was a temporary one, currently, this is a material UI-specific issue and thus the fix is also mui specific, so the ideal way would be to create our custom Modal and replace it

cc: @nihal467
