### ISSUE TITLE
Create a new page to expired password reset link

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#3939]
**Describe the bug**

The reset password mail received to the user , states that the link do expires in one hour, but in real, it is not getting expired

**To Reproduce**

https://care.coronasafe.in/password_reset/34724187318f48f93ca80520c8c03a7fa9175144a901c7 ( It is received on october 30th )

**Expected behavior**

Create a page, where all expired links are been redirected to that

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/199764829-3b3829fd-9ca7-4a89-8ef5-10853e7dd082.png)

**Comment by Ashesh3** [comment]
@nihal467 the link seems to have expired as expected. The issue is that the message is shown after the reset button is clicked. Any suggestions on how to revamp this design and show the error message on the page load itself? 

![image](https://user-images.githubusercontent.com/3626859/199766482-8130cec8-2853-4cfd-be91-90dc6af252f7.png)

**Comment by nihal467** [comment]
@Ashesh3 
![image](https://user-images.githubusercontent.com/57055998/199768163-b6ecedca-9340-47dd-906d-1f736f9e7373.png)


something similar to 404 page will be good, when we click on any expired links, they are been redirected to a page saying that " the link is expired, use a new one to reset the account " something like that which make user aware that this link doesn't work anymore and a button to return them to the login page
