### ISSUE TITLE
Cypress: New Patient Creation

### ISSUE THREAD

**Issue by rabilrbl** [coronasafe/care_fe#4233]

**Comment by ShivamJhaa** [comment]
@khavinshankar I would like to work on this issue, can you please assign me this task?
Thank You!

**Comment by ShivamJhaa** [comment]
@khavinshankar , @nihal467  While writing the test for new patient creation, I encountered the following error.

Even after typing the phone number when we click on Add Patient button, we get the following error:

![Screenshot from 2023-05-26 19-55-23](https://github.com/coronasafe/care_fe/assets/86483059/12b4159f-724c-4c74-a49e-9c300baa98ea)

We can clearly see that the phone number typed is a valid one.

I tried debugging this and logged the input value we are getting from the form. The value we get is something like: "919994565656" and when we try to take out the phone number from this input we get an undefined value. One strange is if I edit anything when the test is paused and again try to submit the form, this time we get "+91 956465656" (notice the + sign and gap) and we are able to successfully retrieve the phone number from it using `parsePhoneNumberFromString` method. Check out the screenshot for more info:

![Screenshot from 2023-05-26 20-02-09](https://github.com/coronasafe/care_fe/assets/86483059/29a07702-a061-4ef2-866b-c698d77810f1)

The first set of console values are when the phone numbers are typed using cypress, the next one is when I tried editing one of them and re submit the form.

Can anyone of you please take a look at this. Thanks!

**Comment by khavinshankar** [comment]
@ShivamJhaa try all these formats
- "919994565656"
- "+919994565656"
- "+91 9994565656"
- "+91 99945-65656"
one of these might work.

@GokulramGHV can you help @ShivamJhaa out

**Comment by ShivamJhaa** [comment]
> @ShivamJhaa try all these formats
> 
> * "919994565656"
> * "+919994565656"
> * "+91 9994565656"
> * "+91 99945-65656"
>   one of these might work.
> 
> @GokulramGHV can you help @ShivamJhaa out

Strange none of them worked, still giving the same error.
![Screenshot from 2023-05-27 13-21-03](https://github.com/coronasafe/care_fe/assets/86483059/0915f852-7709-4503-967e-d03324941ef4)

**Comment by nihal467** [comment]
@ShivamJhaa 
![image](https://github.com/coronasafe/care_fe/assets/57055998/e5701c5f-1b71-486e-a0ce-c4323cfb4a54)

I ran your draft PR #5549  in my local, and the patient creation is successful, check the screenshot attached, can you check once again, what is the problem


CC: @rithviknishad @khavinshankar

**Comment by ShivamJhaa** [comment]
@nihal467 Actually I have not added any check in the end to verify that the Patient is created, that's why it is showing passed. If you will pause the test ([here](https://github.com/coronasafe/care_fe/pull/5549/files#diff-85edc6c535fd4c7cef250d5a68bb562c3fd75a82654e2de0b0227413d5840bfaR92) add `cy.pause()` )at the end you will see that after clicking on the Add Patient button instead of creating the patient it throws the error.

**Comment by ShivamJhaa** [comment]
And due to this only we are not able to get the URL of the patient created which is needed for the next test cases and hence they are failing.

**Comment by nihal467** [comment]
@ShivamJhaa 

![image](https://github.com/coronasafe/care_fe/assets/57055998/ec4fcef2-ff61-4606-95db-1ed4504e2f61)

- keep the phone number constant as "9999999999" for now.
- Once you enter the phone number, a pop-up will appear, similar to the screenshot above. You need to click on "I confirm that the suspect/patient I want to create is not on the list" and continue filling in the remaining fields.
- try solving this, because you are using " force: true " in the code to input data to the phone number field, which disables all pop-ups and related validations. so solve without using force:true
- For now, only include the mandatory fields. Once you figure it out, you can input data into the optional fields.

**Comment by ShivamJhaa** [comment]
> @ShivamJhaa
> 
> ![image](https://user-images.githubusercontent.com/57055998/241570190-ec4fcef2-ff61-4606-95db-1ed4504e2f61.png)
> 
> * keep the phone number constant as "9999999999" for now.
> * Once you enter the phone number, a pop-up will appear, similar to the screenshot above. You need to click on "I confirm that the suspect/patient I want to create is not on the list" and continue filling in the remaining fields.
> * try solving this, because you are using " force: true " in the code to input data to the phone number field, which disables all pop-ups and related validations. so solve without using force:true
> * For now, only include the mandatory fields. Once you figure it out, you can input data into the optional fields.

@nihal467 
This solution will work for the phone number field but we will still have an invalid emergency phone number and this will not allow us to create a new patient.

**Comment by rithviknishad** [comment]
Have you removed `force:true` from all fields?
Do not use `force:true` unless absolutely necessary.
Keep pushing changes to your draft PR so that we can have a look at it.

**Comment by ShivamJhaa** [comment]
Removing `force: true` throws this error: 

![Screenshot from 2023-05-30 16-13-15](https://github.com/coronasafe/care_fe/assets/86483059/747efe52-ce39-4ce9-9e77-6e4c2a4a1e8d)

**Comment by rithviknishad** [comment]
Why do u think this happens?

**Comment by rithviknishad** [comment]
Have you pushed your changes?

**Comment by ShivamJhaa** [comment]
I was able to fix the error, by using ID as a selector for the input box (this also removed the need of `force: true`). I have pushed all the changes.
