### ISSUE TITLE
Add Create asset button in asset view page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#4290]
**Is your feature request related to a problem? Please describe.**

Currently, the Create asset button is only present on the facility page

**Describe the solution you'd like**

Add a button to Create asset button on the asset view page.

![image](https://user-images.githubusercontent.com/57055998/207261855-3814fda3-8aa5-4f97-8d13-0b9a4a754759.png)

**Comment by Ashesh3** [comment]
@nihal467 Currently asset creation is specific to a particular facility, when you click the create asset button on a facility page, you see a list of locations within the facility itself where you can create assets. 

We can add a create asset button here on the asset page and show facility selection menu in the creation form itself so that the user can select the facility + location, is that what you are looking for?

**Comment by nihal467** [comment]
@Ashesh3 
![image](https://user-images.githubusercontent.com/57055998/207266398-f5f1b2c0-562f-47be-ba97-b94b6743f03c.png)

I think similar to the Add patient button on the page, when we click on the button, a pop-up comes in and asks for the facility name then we proceed to the asset creation page. 

We will discuss the best solution in the EOD call and then only start work on this issue
