### ISSUE TITLE
Add patient details button is jumping when we open advanced patient filters

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4353]
**Describe the bug**
In the patients' list page, the add patient details button is jumping when we open Advanced Filters.

**To Reproduce**

1. Go to patients list page
2. Open advanced filters

**Expected behavior**
It shouldn't jump.

**Screenshots**

https://user-images.githubusercontent.com/25143503/208308510-655223e1-99f2-4181-b5a4-5701fbc5a42b.mp4

**Comment by khavinshankar** [comment]
@rithviknishad  
The jumping around seems to be caused because of the useExport hook. We are exporting ExportMenu and ExportButton JSX components from the useExport hook, so as the useExport hook is called at every render, these also are changing _(function signatures)_ and rerendered. The jumping is because of the difference in time taken to render the icons used inside the 2 above-mentioned functions. 

I think converting the hook to a component should fix it, what are ur thoughts?

**Comment by rithviknishad** [comment]
@khavinshankar I understood the problem. I should make sure I stop inlining components 😅 

Btw, do you mean to refactor out the ExportMenu, ExportButton, and _CSVLink outside of the hook?

Or to create two components ExportMenu, and ExportButton that replicates the functionality of the useExport hook inside it?

**Comment by khavinshankar** [comment]
@rithviknishad something of that sort

**Comment by rithviknishad** [comment]
@khavinshankar I think it should work, but I wonder how it also affects the add patient details button too?

**Comment by naman114** [comment]
The buttons seem to be jumping on several screens when the sidebar is opened

https://user-images.githubusercontent.com/57593654/208493632-e3bcb511-e6f8-4d23-be21-cb5470b0deea.mp4

@gigincg @khavinshankar @rithviknishad
