### ISSUE TITLE
Goodbye to Rolebtn component from CARE

### ISSUE THREAD

**Issue by patelaryan7751** [coronasafe/care_fe#4370]
**Describe the bug**
All Existing Rolebtn would be replaced by ButtonV2

**Comment by nihal467** [comment]
@patelaryan7751 what is status of the PR

**Comment by patelaryan7751** [comment]
@nihal467  i would be working on it

**Comment by meeddhhaa** [comment]
Hi @mathew-alex @rithviknishad @nihal467 can you please provide some more information regarding this issue? I'm new here and I'd love to work on this issue.

**Comment by rithviknishad** [comment]
@meeddhhaa some buttons are allowed only for certain user types/role. So we had a seperate `RoleButton` component that serves the purpose.

However, its a legacy component since it was built in early days to work along with material ui and all. Nowadays we have `ButtonV2` tailwind based component which is widely used. This custom component also supports disabling based on user type, which can be specified with the `authorizedFor` prop.

This way we won't need to use seperate components to restrict access, just use the same ButtonV2 component and add authorizedFor=___.

This helps in keeping designs consistent and maintaining the codebase in long run.

**Comment by meeddhhaa** [comment]
@rithviknishad  Cool, got the gist. I'll set up the codebase and start working on this, thanks!

**Comment by rithviknishad** [comment]
@meeddhhaa any updates on this?
