### ISSUE TITLE
Very high memory usage!

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#4374]
**Describe the bug**
When [care.coronasafe.in](https://care.coronasafe.in/) is opened, a lot of the system resource is taken away :/ 

Memory usage in my system:
- Before opening care: **13.0 GB**
- After landing in care: **15.5 GB** (this would be biased with my OBS screen recording too).
- After closing care: **13.2 GB** (with screen recorder continued to be on).

So it's using **2.3 GB**!!???

**To Reproduce**

1. Go to care.coronasafe.in

**Screenshots**

https://user-images.githubusercontent.com/25143503/208592169-cc7d4782-15a7-406b-ac6c-d53d7670c3b3.mp4

**Desktop:**

- OS: Ubuntu 22.10
- Browser: Mozilla Firefox 107.0.1

cc: @gigincg

**Comment by Ashesh3** [comment]
Could you also check this in `about:memory`? Load up care_fe fully in a window, then go to `about:memory` in a new window and click Measure, that should show you exactly what is taking up memory.

At first glance, it seems to be due to the login page animations. 
![image](https://user-images.githubusercontent.com/3626859/208594589-ef247ed5-66d0-4b00-b81d-51aec5517d4d.png)

(An old deploy preview without login page animations)
https://deploy-preview-2786--care-net.netlify.app/
![image](https://user-images.githubusercontent.com/3626859/208594330-709db750-a7d7-45c3-855b-ed2a4b9d5734.png)

**Comment by rithviknishad** [comment]
@Ashesh3 yup same!

![image](https://user-images.githubusercontent.com/25143503/208596157-e6d055c3-457c-49f4-8c2c-a22506b02b01.png)

**Comment by rithviknishad** [comment]
I can confirm that the high memory usage does disappear after logging in.

**Comment by Ashesh3** [comment]
> I can confirm that the high memory usage does disappear after logging in.

Same here!

**Comment by khavinshankar** [comment]
@rithviknishad @Ashesh3 this issue seems to be firefox specific, doesn't happen in chrome for me but only happens in firefox :thinking:

**Comment by rithviknishad** [comment]
A bug reported 10 years ago: https://bugzilla.mozilla.org/show_bug.cgi?id=786108

Not sure if this would help: https://codepen.io/tigt/post/improving-svg-rendering-performance#to-animate-svg-give-it-a-div-parent-and-animate-that-instead-16

![image](https://user-images.githubusercontent.com/25143503/208841818-7a92e45d-e510-4365-9b8d-8730b5de7162.png)

cc: @skks1212

**Comment by shivankacker** [comment]
@rithviknishad can you try replacing the svg with a png and see if that works?

**Comment by rithviknishad** [comment]
Yeay! Having it as PNG seems to be using very less memory

![image](https://user-images.githubusercontent.com/25143503/209054278-a02822b1-3858-4eda-9899-496712d5c934.png)
