### ISSUE TITLE
Assign/Update bed : optimisation

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5082]
**Is your feature request related to a problem? Please describe.**
Currently, since CARE is limited to 10bedicus managing 10-15 beds only in every hospitals. 

However, we are working towards expanding that to cover many more beds in a hospital. (eg: smartICU, discussions to also add general beds into CARE)

When close to 100 beds are registered in CARE in a single facility, it becomes difficult to choose the current bed from the dropdown in the form.

**Describe the solution you'd like**
Instead of asking for Bed No. and listing all the beds in the facility,

Capture location (with dropdown of all locations) and then have a second dropdown for beds (with all beds registered in the location).

**Comment by gigincg** [comment]
@aparnacoronasafe 

Instead of listing only Bed Names in the Bed search. If we show `Bed - Location` and allow searching by `Bed-Location` would that work?

So `Bed 1` in location `RICU` will be listed as `Bed 1 - RICU` and searching `RICU` will give you the result.

Adding another Dropdown makes the experience bad IMO.

**Comment by aparnacoronasafe** [comment]
I agree @gigincg

**Comment by siddnikh** [comment]
It's already been implemented in some earlier pr. We can close this issue.
