### ISSUE TITLE
The `/session-expired` route shows "Page Not Found" instead of "Session Expired"

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5232]
**Describe the bug**
The `/session-expired` route shows "Page Not Found" instead of "Session Expired"

**To Reproduce**

1. Wait for session to expire

**Expected behavior**
The `/session-expired` route should be showing "Session Expired" component.

**Screenshots**
![image](https://user-images.githubusercontent.com/25143503/229767922-7e7c0803-a18f-4176-8154-3a63cf94fb8f.png)

**Desktop (please complete the following information):**

- OS: Ubuntu 22.10
- Browser: chrome
- Version 111.0.5563.146 (Official Build) (64-bit)

**Comment by CouldBeFree** [comment]
I am working on this issue

**Comment by CouldBeFree** [comment]
I investigated the issue, so when the token expires, the user is logged out and redirected to the page /session-expired.
So in this case all works correctly.
The issue occurs for logged-in users if manually enter /session-expired in the URL.
Users see a 404 page because in the router configuration for logged-in users, there is no such route (session-expired)
So possible solution is to not allow logged-in users to enter this route, it should be allowed only for non-logged users.
I need your approval @rithviknishad

**Comment by rithviknishad** [comment]
Yes @CouldBeFree 
If the session is not expired and if user manually enters such a route, how about we redirect them back to the previous valid route if any is present in the history stack (checkout `useAppHistory` custom hook). If no history is present we may route them to `/` which will redirect them to `/facility` automatically.

**Comment by CouldBeFree** [comment]
I will implement such logic.
Thank you for the updates.
@rithviknishad

**Comment by CouldBeFree** [comment]
How to get permission, to be able to push my branch with fix and create pl?

**Comment by rithviknishad** [comment]
@CouldBeFree you may create a branch in your fork, and raise a PR to this repo's develop branch.

**Comment by rithviknishad** [comment]
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
