### ISSUE TITLE
Discharge summary is missing multiple information

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5246]
points to be discussed are below :

[test-march-fifthweek-Discharge_Summary.pdf](https://github.com/coronasafe/care_fe/files/11158912/test-march-fifthweek-Discharge_Summary.pdf)

![image](https://user-images.githubusercontent.com/57055998/230083846-14d05026-af24-476f-a9fc-ccb20ef9bc69.png)

- symptoms are recorded in the summary report, but the date on onset symptoms are not shown in the discharge summary

![image](https://user-images.githubusercontent.com/57055998/230084846-1777b4de-92f0-420c-ab6c-c9482cef14e8.png)

- weight, height, and category are not showing in the patient discharge summary
- provisional diagnosis and diagnosis are not showing in the patient discharge summary

![image](https://user-images.githubusercontent.com/57055998/230085566-95b9d861-ef65-4038-b6a6-2cd721fe0917.png)

- only prescription medicine are shown and no PRN prescriptions are shown in the discharge summary
- in consultation history, only admitted dates are showing, there is no info on previous discharge history

![image](https://user-images.githubusercontent.com/57055998/230090229-26dd8840-2285-453f-a3cb-53999ed11b0c.png)

- present health condition, ongoing medication, allergies, blood group, insurance details are not mentioned in the discharge summary

[test-march-fifthweek-Discharge_Summary (after discharge).pdf](https://github.com/coronasafe/care_fe/files/11159319/test-march-fifthweek-Discharge_Summary.after.discharge.pdf)

![image](https://user-images.githubusercontent.com/57055998/230097100-12025b3e-c57e-4507-b0f4-aef839fe8ff3.png)

- once we discharge a patient, the medicine entered in the discharge pop-up is not visible in the discharge summary
- once we discharge a patient, the medicine we entered while create a patient consultation is not visible in discharge summary
- the discharge note, and discharge reason is not visible in the discharge summary 

![image](https://user-images.githubusercontent.com/57055998/230098134-05c37f2c-0744-4458-80fc-9ebedfc24fa1.png)

- current health is not recorded anywhere in the platform anymore

**Comment by nihal467** [comment]
@aparnacoronasafe can you go through the missing information and comment in, whether these are intentionally missed out, or we need to add it

**Comment by aparnacoronasafe** [comment]
The items to be added to the discharge summary:

- [x] Date of onset of symptoms
- [x] Weight and Height 
- [x] Provisional Diagnosis
- [x] Diagnosis
- [x] ONLY if the patient is COVID positive, the discharge summary should have COVID Disease status and vaccination details.
- [x] PRN Presciption along with normal prescription
- [x] Health status at admission (History of present illness), Ongoing medication at admission (Ongoing medication) 
- [x] Allergies
- [x] Blood group
- [x] Discharge details- Discharge reason, Discharge prescription, Discharge PRN Prescription and discharge notes
- [x] Hide Care Patient ID
- [x] Status during consultation
- [x] Procedure
- [x] When any of the fields have no data, DO NOT show the field in discharge summary


Leaving out some info because:
- Category- since the categorization is loosely based on 4 categories without any clinical definition. It is only a tool used internally and does not have much clinical relevance outside. 
- Consultation history need not be detailed out in the discharge summary 

EDIT THE FORMAT OF THE DISCHARGE SUMMARY FOR INFORMATION TO APPEAR IN THE FOLLOWING ORDER
___________________
**Hospital Name
Patient Discharge Summary**

Name of Patient :                                                        Gender:                                              Sex:
Age:                                                                              DOB:                                                  Blood Group:
Address:                                                                       Ph. No.      

**Admission Details** (as a heading)
Status during consultation:
Date of Admission:                                                     IP No:       
Symptoms at admission: along with date of onset of symptoms  
Medication history (commorbidities)
Health status at admission (History of present illness)                                                    

**Treatment Summary** (as a heading)
Diagnosis:
If COVID Disease status is positive, then show COVID Disease status, COVID Test result Date: COVID Vaccination details.
Prescription (Table)
PRN Prescription (Table)
Investigations conducted (table)
Procedure: 

**Discharge Details** (as a heading)
Date of Discharge:                                               Discharge Reason:
Discharge prescription (table)
Discharge PRN prescription (table)
Discharge Note: 

Treating physician (verified by in consultation form)

**Comment by nihal467** [comment]
@sainak can you provide an ETA

**Comment by sainak** [comment]
> @sainak can you provide an ETA

Will be done by thursday eod

**Comment by nihal467** [comment]
@sainak we are having our production release schedule this Friday, so make sure that you push the fix before Thursday EOD itself, and don't delay it much further!
