### ISSUE TITLE
Recommend Discharge data is not shown in patient consultation page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5271]
**Describe the bug**

a patient is recommended discharge when we are filling a patient log update, the saved data is not shown anywhere on the patient consultation page.

Note: When we click "View details" button in the existing log update card, we can see the data 

**To Reproduce**

1. Go to https://care.coronasafe.in/facility/aec039c8-d3e2-4691-a1b6-78b80d8530ed/patient/c278ebfa-5f30-4f9b-8f23-3acfd158f46c/consultation/53b241cb-e589-4d76-9fe5-796505cc4cf3
2. Create a log update with recommend discharge selected
3. come to patient consultation page
5. See error

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/230611817-028ee0c6-c9da-4898-8ad0-9c601ebcdf08.png)
![image](https://user-images.githubusercontent.com/57055998/230611855-393e68eb-d742-4916-8740-c6e0d9f0752d.png)
![image](https://user-images.githubusercontent.com/57055998/230611966-7e6db133-d31b-4b9e-a0f2-3d9d545713c5.png)

**Comment by aparnacoronasafe** [comment]
**Relevance of "recommend discharge"**
The reason we have an option to Note "Recommend Discharge" in log update and then a separate "Discharge from CARE" option is because in most cases, the Treating physician would clear the patient for discharge, but the actual discharge may only happen after one of multiple of the following events are done:
1) The patient is on an infusion (medication given through drip) and the doctors may have asked nurse to wait 2-3 hours for drip to complete before sending the patient
2) The patients bill may need to be settled
3) The patient insurance claim process maybe ongoing
etc. 

Therefore the actual discharge (noted in CARE through "discharge from CARE" on patient dashboard) may only be done hours after the treating physician recommends discharge. 

**To-Do**

- [x] Design a flag for "recommended Discharge" to be visible on the patient list and patient dashboard. the design may be kept consistent with the design for "Action". refer to #5272 . or better the design of actions may be reimagined keeping this use-case also in mind.
