### ISSUE TITLE
ICD-11 Search enhancement

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5293]
The ICD-11 Diagnosis search field in CARE is not optimized. 

Analyze the search logic at https://icd.who.int/ct11/icd11_mms/en/release and implement the same in CARE

**Comment by rithviknishad** [comment]
Currently, we do not store enough attributes/information about ICD11 Diagnoses in the ICD11 in-memory database in our backend.

A possible solution is to use [ICD API](https://icd.who.int/icdapi) (see [Swagger Docs](https://id.who.int/swagger/index.html)). We could get an API key or self-host it.

It may break things since we are unaware if they might make changes in the ICD v11 API itself.

A possible workaround for this issue could be to use ICD API to query, extract the entries out, match them with the ICD11 entries present in our backend, and give that response.

**Comment by nihal467** [comment]
@rithviknishad @aparnacoronasafe any update on this issue, was it discussed in the call

**Comment by rithviknishad** [comment]
We've decided to use the ICD API docker; FE would hit the ICD API for searching; and use the `theCode` attribute to perform a lookup on to care's ICD entries upon form submission.

**Comment by rithviknishad** [comment]
we may not be able to use `theCode` for lookup. Attaching an example entity with `"theCode": "PE95/"` and `"title": "Assault by exposure to or harmful effects of other inorganic substances"`. This entity is not present in our `icd11.json` nor the spreadsheet export from ICD11's browsing tool.

A similar one exists with `PE95`, title: `"Assault by exposure to or harmful effects of other or unspecified substances chiefly nonmedicinal as to source"`.

<img width="1710" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8af60147-25d2-4335-951c-01ac0c2d4a35">

**Comment by rithviknishad** [comment]
All results with: `entityType > 0` has this mentioned issue.

**Comment by rithviknishad** [comment]
Closing as continued in #8080
