### ISSUE TITLE
Discharge and live patients are shown in the patient creation form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5372]
**Describe the bug**

when we enter a number in the patient creation form, it is showing all the patient names irrespective of whether the patient is already live or discharged from the care

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/57055998/233853310-c9e3787b-87bb-4a70-99bc-07d4f4a38d9b.png)

**Comment by aparnacoronasafe** [comment]
This is expected behaviour. 

Discharged patients must show up for sure. 

LIVE patients are also shown in the list because otherwise, if one hospital in CARE is not updating patient data properly, and have kept the patient LIVE in CARE even after the patient may have left the hospital, no other hospital will be able to access the patient card later.

Since we authenticate with DOB, the process should work fine
