### ISSUE TITLE
Multiple Bug in Shifting Form

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#5416]
**Describe the bug**
EPIC Issue Ref : https://github.com/coronasafe/care_fe/issues/5393

- [ ]  Origin Facility staff is unable to update the following status in the shifting form: Destination Approved, Cancelled ( Ref: [#1271](https://github.com/coronasafe/care/issues/1271) 

- [ ] when i mark a patient shifting update status as complete, only the shifting card status is updated, the patient is not discharged from the origin facility ( Ref : #5389 )

- [ ] Destination Facility staff is unable to update the following status in the shifting form: Destination Approved, Complete

**Comment by Ashesh3** [comment]
- [x] Origin Facility staff is unable to update the following status in the shifting form: Destination Approved, Cancelled - Should be fixed by https://github.com/coronasafe/care/pull/1276
- [x] Destination Facility staff is unable to update the following status in the shifting form: Destination Approved, Complete - Should be fixed by https://github.com/coronasafe/care/pull/1276
