### ISSUE TITLE
Feature: Support for printing Prescriptions 

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#5701]
**Is your feature request related to a problem?**
All prescriptions of Non-Admission Consultations should be printable with a check list like flow similar to bulk administer of medicines.

All discharge prescriptions should be printable during discharge. This is apart from the discharge summary.

**Comment by aparnacoronasafe** [comment]
@rithviknishad 

All prescriptions should be printable. (including admitted patients).

This is because the hospitals continue to function using paper files parallel to the digital system. Allowing them to print out the active prescription would help the nurses to add those to the files. 

To follow a simple model, we can just have 1 format for printing prescriptions.
suggestive format: https://docs.google.com/document/d/1mF9GDLx-3wgf-ayvcAXPy428lVaZbvO8T8y_LD50nXA/edit?usp=sharing

**Comment by rithviknishad** [comment]
Closing as duplicate of #8258
