### ISSUE TITLE
Use DialogModal instead of SlideOverCustom for Weekly working hours of user

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/care_fe#6009]
**Describe the bug**
We are using SlideOverCustom to edit the `Weekly Working Hours` for users which seems unnecessary and takes a lot of space. Instead, we can use DialogModal to do the same, it would be much more cleaner.

**To Reproduce**

1. Go to https://care.coronasafe.in/users
2. Click on `Set Weekly Working Hours` for any user
3. See error

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/70687348/8d912ad0-21b5-4fc2-9f91-58400a869659)

DialogModal would look like this:
![image](https://github.com/coronasafe/care_fe/assets/70687348/69aa4270-6c12-492a-9d84-b98058b83b3a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Pranshu1902** [comment]
What's your opinion @khavinshankar @nihal467 @gigincg

**Comment by Ashesh3** [comment]
The decision to implement the SlideOver component was made in order to maintain consistency with the user interface of the other buttons on the User Info card. The Skills and Linked Facilities buttons both utilize the SlideOver component, and it was considered to provide a similar user experience for all buttons. While this may be a low priority issue, it is open for discussion!

**Comment by Ashesh3** [comment]
Closing after an internal discussion. Refer to the above comment for more details.
