### ISSUE TITLE
Patients List: Empty emergency phone number filter applied by default on mount

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6101]
**Describe the bug**
An empty filter for emergency phone numbers (and hence causes `page` and `limit` filters) to be applied too by default.

**To Reproduce**

1. Open https://care.ohc.network
2. Go to patients tab
3. Observe url, it goes to `/patients` and then jumps to `/patients?page=1&limit=12&emergency_phone_number=` immediately

**Expected behavior**

Behavior should be similar like other tab pages (`/assets`, `/facilities`).
The empty `emergency_phone_number` filter shouldn't be applied and hence should be navigated to `/patients` itself by default.

**Screenshots**
<img width="1160" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/8ac9edc1-bcef-480e-b158-4f9b76ac5099">

**Comment by mustafaazad03** [comment]
Hi @rithviknishad ,
I solved this bug, will I make a PR?
![image](https://github.com/coronasafe/care_fe/assets/97380192/dd610c0d-dece-402f-a971-2c310c590d4d)

**Comment by Ashesh3** [comment]
> Hi @rithviknishad , I solved this bug, will I make a PR? ![image](https://user-images.githubusercontent.com/97380192/264398920-dd610c0d-dece-402f-a971-2c310c590d4d.png)

Yep, feel free to make a PR and link to this issue.

**Comment by mustafaazad03** [comment]
thank you @Ashesh3, Can you check this PR !!

**Comment by mustafaazad03** [comment]
please check this PR @rithviknishad

**Comment by print-Sathvik** [comment]
Hey @mustafaazad03, sorry for creating PR on the same issue. The last time I checked this at night, there was no one assigned to this and there wasn't any activity on this issue. So I started working and forgot to assign it to myself. Guess we started almost at the same time.

I checked your latest PR, setting the limit to null removes it from the URL but that breaks the purpose of limit. There are 14 patients displayed per page instead of 12. Also the pagination component which is used to navigate to different set of patients is replaced by red colored text saying "Do not render Pagination component, when limit is <= 0"

I changed my PR to a draft PR. So let me know if you can resolve this, I will close my PR.

**Comment by mustafaazad03** [comment]
Hey @print-Sathvik ,
It's OK, No problem but I have solved that issue can you check the corrections?
I am making PR
