### ISSUE TITLE
BUG: date picker- asset service update

### ISSUE THREAD

**Issue by aparnaegov** [coronasafe/care_fe#6217]
**Is your feature request related to a problem? Please describe.**
when adding a new service log in update asset (https://care.coronasafe.in/facility/1210229b-711a-46e6-ab0a-207c4808e32e/assets/acd6a5e5-b344-4164-aa80-40a278b87a9a/update) , in service details, when trying to pick a date by clicking on date picker, the date does not appear in the field. 

The field to type in date is working fine

**Describe the solution you'd like**
Fix date picker on the calendar

**Comment by suprabathk** [comment]
I would like to work on this

**Comment by nihal467** [comment]
@aparnaegov can you recheck the bug, I can't replicate it, @rithviknishad can you also give the bug a look

**Comment by rithviknishad** [comment]
<img width="668" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/6ef4ae80-39cb-40d3-92e7-2c49650b33aa">

**Comment by nihal467** [comment]
@suprabathk 
![image](https://github.com/coronasafe/care_fe/assets/57055998/1577efb9-7f41-4599-9411-e11b6ff45479)

The bug here is that, initially, when we click the last service detail, the calendar sometimes, becomes only half visible, so, when we try to click on the date to select, on the first click, it makes the component fully visible, and on the next click only the date selection takes place.

The above situation shouldn't be the ideal case, on the first click itself the user should be able to select the date

Note: This bug won't occur, if the user manually scrolls and makes the component fully visible first and click on the date.
