### ISSUE TITLE
Bug: Medicine Administrations table starts with an additional hour offset to the future

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6323]
**Describe the bug**

**To Reproduce**

1. Go to Medicine Administrations Table

**Expected behavior**
The additional 1-hour column (where administrations cannot be made at the present time) should not be present.

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/25143503/6cc46bbe-e4ec-4595-b7f2-f9cf3f554daa)

Reported by @nihal467

**Comment by print-Sathvik** [comment]
End date: 23/09/2023

**Comment by rithviknishad** [comment]
The latest date should always be the latest of  all last administered date.

i.e. Medicine A is last administered 23rd 10:02 AM, Medicine B is last administered 23rd 11:04 AM, then it should show the column upto 23rd 11:00 AM (because that column contains all administrations between 11 AM and 11:59 AM)

**Comment by print-Sathvik** [comment]
> End date: 23/09/2023

Sorry for taking an extra day. Before assigning this issue to myself I got the solution and thought that I will be completing it in few minutes but I misunderstood the issue earlier before your explanation. After trying out a different approach I noticed that the 1st administration is not being displayed in the table when the 1st administration was sent into second page of paginated table. I thought it was because of my work and I was making changes to my work but that bug is already existing at care.ohc.network. I fixed that too.
