### ISSUE TITLE
Restrict patient entry in CARE without filing consultation page

### ISSUE THREAD

**Issue by Deepjyoti14** [coronasafe/care_fe#6423]
**Is your feature request related to a problem? Please describe.**
Patients are shown in care without consultation filed.

Observation: Sometimes staffs at spokes forgets to fill the consultation page. Since the patient is entered, they think they will file consultation later and it remain unfilled. Also, these types of entries are not being counted in state dashboard active patient number count.

**Describe the solution you'd like**
I think if we make it mandatory to fill both the page "patient details and consultation page" to successfully admit a patient in CARE will solve the issue.

**Comment by Deepjyoti14** [comment]
@nihal467 @aparnacoronasafe

**Comment by aparnaegov** [comment]
@Deepjyoti14 

We are allowing users to register a patient and then later come back and file consultation, so that they have enough time to collect all consultation details before attempting to file consultation.
The worry is, if we allow registration of patient and filing consultation together, the registration of patient also may get delayed. 

It is always a good idea to allow nurses to approach a large task in steps, Registration and then filing consultation, so that atleast 1 of the step gets performed. and then they can come back to the next.

However, we also know that some nurses forget to, or leave out filing consultation.

This is why we have added a label on the patient card for "No Consultation Filed"

The reason why such patients are not shown in dashboard is because dashboard today is only for patient admitted to the ICU. And admission to ICU is marked in consultation.

This is something that may be taken care of by strengthening training.
