### ISSUE TITLE
Hide Camera Feed Tab for bed with no camera attached

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6475]
**Describe the bug**

When we assign a patient to a bed which is not having any camera been configured to it, it is still showing feed button in the patient consultation page

**To Reproduce**

1. go to patient tab
2. assign a patient to a bed which has no camera been assign to the bed
3. go to the patient consultation page and you will be seeing feed button for the patient

**Expected behavior**

When a patient is assigned to a bed which has no preset to it, we should be hiding the feed button in the patient consultation page

**Screenshots**

<img width="960" alt="image" src="https://github.com/coronasafe/care_fe/assets/57055998/f5472f23-8378-403d-8a5c-314b0de54d7b">

**Comment by shyamprakash123** [comment]
I want to work on this issue, can you please assign me?

**Comment by shyamprakash123** [comment]
@Ashesh3 @nihal467, Is this issue solved? Because it is not showing the feed tab but it is showing the camera feed button in the header title buttons. Link : https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/0e1a1fc1-148b-453d-9f86-04f9e56cf0ff/consultation/47d78e41-fe9f-4b3d-b0b7-9fc4117805b8

User : devdistrictadmin

**Comment by Ashesh3** [comment]
> @Ashesh3, Is this issue solved? Because it is not showing the feed tab but it is showing the camera feed button in the header title buttons. Link : [care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/0e1a1fc1-148b-453d-9f86-04f9e56cf0ff/consultation/47d78e41-fe9f-4b3d-b0b7-9fc4117805b8](https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/0e1a1fc1-148b-453d-9f86-04f9e56cf0ff/consultation/47d78e41-fe9f-4b3d-b0b7-9fc4117805b8)
> 
> User : devdistrictadmin

There is no bed attached to this patient, hence the feed tab will not show. The issue is about hiding the feed tab for patients who have a linked bed to them but that linked bad has no camera asset attached to it.

Example: https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/400cbedd-98d7-4f8f-b835-155ba71cc28d/consultation/6ae67a3d-305b-4404-bfd6-b21b0d0f8426

This patient has an attached bed without a camera, in this case the feed tab should be hidden:
![image](https://github.com/coronasafe/care_fe/assets/3626859/18248974-0ec7-44ac-819a-45245be372a9)

The bed's location is `NICU`
Here's the corresponding asset: (same location)
https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/assets/ed2edbd7-4581-434e-8c6a-4620b4d0a4a0

It's an HL7 monitor and not a camera, there are no cameras in the same location as that bed, so the feed tab should be hidden.

@nihal467 can you double check this message for any corrections?

**Comment by nihal467** [comment]
@shyamprakash123 the comment made by @Ashesh3 is correct and as well as i updated the issue too

**Comment by shyamprakash123** [comment]
> > @Ashesh3, Is this issue solved? Because it is not showing the feed tab but it is showing the camera feed button in the header title buttons. Link : [care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/0e1a1fc1-148b-453d-9f86-04f9e56cf0ff/consultation/47d78e41-fe9f-4b3d-b0b7-9fc4117805b8](https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/0e1a1fc1-148b-453d-9f86-04f9e56cf0ff/consultation/47d78e41-fe9f-4b3d-b0b7-9fc4117805b8)
> > User : devdistrictadmin
> 
> There is no bed attached to this patient, hence the feed tab will not show. The issue is about hiding the feed tab for patients who have a linked bed to them but that linked bad has no camera asset attached to it.
> 
> Example: https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/patient/400cbedd-98d7-4f8f-b835-155ba71cc28d/consultation/6ae67a3d-305b-4404-bfd6-b21b0d0f8426
> 
> This patient has an attached bed without a camera, in this case the feed tab should be hidden: ![image](https://user-images.githubusercontent.com/3626859/279035666-18248974-0ec7-44ac-819a-45245be372a9.png)
> 
> The bed's location is `NICU` Here's the corresponding asset: (same location) https://care.coronasafe.in/facility/a3910fb7-db3d-4ddf-aa39-1f20e61d1453/assets/ed2edbd7-4581-434e-8c6a-4620b4d0a4a0
> 
> It's an HL7 monitor and not a camera, there are no cameras in the same location as that bed, so the feed tab should be hidden.
> 
> @nihal467 can you double check this message for any corrections?

@Ashesh3 I understood the problem and one more thing should I also hide the Camera Feed button in the Top Section of the Patient Dashboard?
