### ISSUE TITLE
remove the "*" from the rhythm field in the patient normal log update

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6584]
**Describe the bug**

The Rhythm field in the patient normal update consultation already has a default value, still, we are marking it mandatory "*"

**To Reproduce**

1. Go to any patient consultation page and click on the log update
2. select the norma log update and check the rhythm field
3. See error

**Expected behavior**

- [ ] remove the "*" from the rhythm field in the patient normal log update

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/e5915ed6-b4ed-47c3-a5df-aa90ce6f6b36)

**Comment by shyamprakash123** [comment]
I want to work on this, can you assign me?

**Comment by shyamprakash123** [comment]
![Screenshot 2023-11-15 193034](https://github.com/coronasafe/care_fe/assets/106866225/f962ced2-2293-47ee-bdf1-0c85e8845f9f)

@nihal467 I'm getting default value of Rhythm as `unknown`. The form is getting submitted with the value `unknown` is this expected behaviour? Should I remove `"*"` in Rhythm field?

**Comment by nihal467** [comment]
@shyamprakash123 its an expected behaviour just remove the * only
