### ISSUE TITLE
Design Enhancement Scope in Shifting Board 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#6636]
**Describe the bug**

Currently, the shifting board has three scroll bars and it doesn't feel good, when we use it

**To Reproduce**

1. Go to shifting board
2. See error

**Expected behavior**

An effective way to utilize the board and make the user experience better

Note: Whoever wishes to work on this issue, get the mock-up design approved in the EOD call, then only, the issue will be assigned to the respective author.

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a2779ee1-eedb-4980-8cab-c61ea1d1bf9d)

**Comment by Arzzam** [comment]
I would like to work on this issue. Can you assign it to me? 
Kindly give and explain the mock up design.
Thank you

**Comment by Pranshu1902** [comment]
- Adjust the height of the shifting component so that the main page scrollbar on the right isn't needed. (Basically when we scroll the filters and heading on top should not go out of screen)
- Add arrows on the left and right side of the component (vertically in the center) for scrolling left and right since the horizontal scrollbar isn't easily visible (Something like this as shown below)
![image](https://github.com/coronasafe/care_fe/assets/70687348/c1405b96-4b1b-48af-a70d-2e5da5dd3363)

**Comment by Pranshu1902** [comment]
@Arzzam you can start working on it

**Comment by Arzzam** [comment]
Ok Thank you. 
I will reach you, If I need any clarifications.

**Comment by Pranshu1902** [comment]
Hey @Arzzam any updates on this?

**Comment by Arzzam** [comment]
Hi @Pranshu1902 
As I see, the board it implemented in different flow, As I 

<img width="1440" alt="image" src="https://github.com/coronasafe/care_fe/assets/92790024/b4ca5371-9881-492a-a257-b9503647357a">

If we wonna set this on top header to be in fixed position, we have to change the rendering methods or we can change by having separate scroll for every columns. 
<img width="1440" alt="image" src="https://github.com/coronasafe/care_fe/assets/92790024/f1b1ef44-40ba-468f-9459-d81a9175295c">

<img width="1440" alt="image" src="https://github.com/coronasafe/care_fe/assets/92790024/728c08f6-7cb3-4bec-9cd5-e80865910843">

We can do it like this and prevent the overflow down to the page and need to change the app router overflow y scroll to max height to the screen and have to change all children pages to have scroll behaviour to prevent whole body scrolling while overflow. so that we won't have the extra scroll when there is no elements are overflow in the main page.

If we have separate scroll for each column, we can have table headers on the top, it will only scroll only the below content.

Provide your suggestion to continue my progress.

Thank you. Give me your suggestions and feedback.

**Comment by Pranshu1902** [comment]
@Arzzam a quick way would be to restrict the height of the component so that the whole page doesn't scroll as you showed in the last screenshot. Also, the arrows need to be placed inside the component and not on the sides, keep it like a floating button. 

I don't think you need to modify it in the app router coz it will affect all pages
cc @rithviknishad

**Comment by Arzzam** [comment]
Yes it will affect, so that have to change the overflow behaviour for the main page and need to apply it to all the specific pages.

**Comment by Pranshu1902** [comment]
@Arzzam Try to do it without modifying the app router. Set a maximum height limit for the component so that it doesn't go out of the screen size probably using tailwind classes like `h-3/4`

**Comment by Pranshu1902** [comment]
@Arzzam any updates? Try to raise a draft PR so that we can also keep track of the progress

**Comment by Arzzam** [comment]
Sorry for the delay, I will finish it and raise PR in this week.
Thank you

**Comment by Arzzam** [comment]
https://github.com/coronasafe/care_fe/assets/92790024/7f4f16dd-856c-4b18-ae6e-653c381e8366


As I told you the extra scroll will be there as the router has to be fixed. I guess the arrows are not required now. If it is required we can proceed with that. 
Currently fixed the extra scroll of the component but it still can affect in some cases I guess.

**Comment by Pranshu1902** [comment]
@Arzzam I checked the code, so you would have to remove `p-3` from the class from here to remove the extra scroll.
https://github.com/coronasafe/care_fe/blob/8aea0cc9139c507b83784986d9d2c4eec7a7baf6/src/Routers/AppRouter.tsx#L139

See if you can get a work around this otherwise, go ahead and modify the `AppRouter.tsx`. Besides that,  do add the arrows, it's a required feature.

**Comment by Arzzam** [comment]
Hi @Pranshu1902,
I have a doubt that when I dynamically add the top and left in the tailwind classNames, It is not working. 

Here I have attached a video that will shows about it, Is there any reason it is not working, I have added class like these in other projects but it worked. I guess it is not worked in oru project thats why I am curious about it.
I have finished everything. I just want to position these buttons dynamically when the screen size changes that why I added like this but it won't work. 
Thanks for your help.

https://github.com/coronasafe/care_fe/assets/92790024/19136622-6473-4d26-b0c4-5043065005cd

Is there any changes required here

<img width="1440" alt="image" src="https://github.com/coronasafe/care_fe/assets/92790024/0bcce8c5-6f54-4974-a8d7-cd7567290603">

**Comment by rithviknishad** [comment]
Could you share the JSX code used to achieve that?

**Comment by Arzzam** [comment]
HI @rithviknishad 

Here, I have attach the screenshot of the code.

<img width="1440" alt="Screenshot 2024-01-01 at 1 34 56 PM" src="https://github.com/coronasafe/care_fe/assets/92790024/5adbbe4f-3cbf-4fc0-a885-44a630bd6a10">

<img width="1440" alt="image" src="https://github.com/coronasafe/care_fe/assets/92790024/0fd73b1d-4d0b-4d6a-bc8c-7faaa93f33da">

**Comment by rithviknishad** [comment]
Dynamic class names won't work. Refer https://tailwindcss.com/docs/content-configuration#dynamic-class-names

You could use CSS styles to achieve this instead. But why does the arrow need to have dynamic absolute positioning in the first place?

**Comment by Arzzam** [comment]
Oh Thanks. 
The arrow needs to be in the [reference](https://github.com/coronasafe/care_fe/issues/6636#issuecomment-1842978389).
It needs to be inside these components. so, I thouht setting the icons absolute and positioning will be great and when we give static values, that can cause different positions for different size of screens. I will update it.
Thanks for your help @rithviknishad

**Comment by Arzzam** [comment]
Hi @rithviknishad @Pranshu1902,
Please take a moment to review my pull request at https://github.com/coronasafe/care_fe/pull/6956.

Thanks for your time and feedback!
