### ISSUE TITLE
Support for self-healing Consultation URL and redirecting `/consultation/:id` to the actual route

### ISSUE THREAD

**Issue by rithviknishad** [coronasafe/care_fe#6761]
**Is your feature request related to a problem? Please describe.**
Currently when we navigate to `/facility/<invalid_id>/patient/<invalid_id>/consultation/<valid_consultation_id>`, we still land on a working consultation details page, however two issues:

1. It's not a valid URL, auto-redirect to healed URL is not working.
2. Breadcrumbs, although show proper data, the `href` of each crumb points to an invalid URL.

**Describe the solution you'd like**

We can reconstruct the URL to point to a proper path since we can successfully retrieve a valid consultation record (since the consultation ID is/must be valid) and the object holds the valid patient and facility `id`.

- [ ] If the facility/patient ID is invalid, perform a redirect to the valid URL.
- [ ] Add a redirect route `care.app/consultation/<consultation_id>` that would redirect to the actual URL (`/facility/:id/patient/:id/consultation/:id`).

**Comment by rithviknishad** [comment]
+1 for making this a generic reusable feature, so that the same can be done eventually for other routes.

Eg: `/facility/<invalid>/assets/id`

**Comment by vivramkrishna** [comment]
I would like to work on it, can you please assign me

**Comment by vivramkrishna** [comment]
@rithviknishad 
I have a small question. Instead of adding a reusable function that redirects to a new URL, which I think adds complexity, especially with the proposed step:

`Add a redirect route care.app/consultation/<consultation_id> that would redirect to the actual URL (/facility/:id/patient/:id/consultation/:id).`

My concern is that when an invalid URL is entered, data is already fetched. Then, when redirecting to "consulation/:id," data is loaded again. If we need to perform a redirect, we require both facilityId and patientId. Upon redirecting to "/facility/:id/patient/:id/consultation/:id," the correct URL loads the data again. I consider this approach to be increasing complexity.

What if we modify the URL in place, for example, "facility/<invalid_id>/patient/<invalid_id>/consultation/<valid_consultation_id>"? If it's invalid, we can change it in place without any redirect to the correct details.


I am  thinking for a reusable function to do it in place

**Comment by konavivekramakrishna** [comment]
@rithviknishad

**Comment by vivramkrishna** [comment]
@rithviknishad 
can I proceed with doing it in, in place

**Comment by rithviknishad** [comment]
Yes

**Comment by rithviknishad** [comment]
However, a new route is also to be added: `/consultation/:id` which would redirect to the actual facility+patient contextual consultation URL.

Multiple data fetching can be prevented because, the component does not change right? Only the route URL would change without the component tree having any changes right?
