### ISSUE TITLE
Clean up left nav menu

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6920]
**Is your feature request related to a problem? Please describe.**
Today, the left side nav menu on CARE contains many redundant options. Hiding those and cleaning up the options will improve UX.
<img width="198" alt="Screenshot 2023-12-26 at 3 33 37 PM" src="https://github.com/coronasafe/care_fe/assets/67050716/4bcaa0aa-e46e-4a29-bd84-da0f7c66cb89">

**Describe the solution you'd like**
Change options to have:
1) facility
2) Patients
3) Assets
4) Shifting 
5) Users
6) Notifications
7) Dashboard
MORE...
8) Sample test
9) Resources
10) External results
11) Notice board

Show more will only be expanded upon clicking on it.

**Comment by AshrafMd-1** [comment]
I want to work on this issue. Can you assign this to me

**Comment by gigincg** [comment]
@aparnacoronasafe Please specify what is the issue here? The Sidebar is scrollable and the space is utilized properly with the current layout. Adding a "Show More" button in a section that has a scroll doesn't make sense. 

Think of the existing Sidebar as a good UX of "Show More" which is an smart infinite scroll.

**Comment by bodhish** [comment]
closing this for now
