### ISSUE TITLE
Occupation of patient to be tracked

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#6945]
https://care.coronasafe.in/facility/eeb23cb7-1524-479a-825e-660311386b47/patient/51ff0682-065d-4e25-bcc6-fb1b682642fb/update

Patient registration form, add a field at the bottom of the "Personal details" section for "Occupation", with dropdown with the following options:
"Student/ Businessman/ Health care worker/Health care lab worker/ animal handler/ any other"

**Comment by sagarkori143** [comment]
I would like to take this one!

**Comment by sagarkori143** [comment]
@aparnacoronasafe 

Should this field also be marked as mandatory?
And are these options okay and sufficient?
![image](https://github.com/coronasafe/care_fe/assets/129517558/374e0469-1f11-401d-8936-927ae06fff2f)

**Comment by sagarkori143** [comment]
Also @rithviknishad  @aparnacoronasafe  @nihal467 @AshrafMd-1 
I have created the required Occupation field and I inspected results in console and ensured that the occupation data is going through handleSubmit process but this data is not being saved into the database because when I again go to edit patient after submitting all the details, the occupation field there is again empty. Here is what I have done so far:
1) Defined OCCUPATION_TYPES in Constants.tsx
![image](https://github.com/coronasafe/care_fe/assets/129517558/e694b1e6-528b-4d09-bc6f-6bcc98f7883b)



2) Defined occupation modal as strings in models.tsx
![image](https://github.com/coronasafe/care_fe/assets/129517558/e053774b-416c-4c22-827d-49b0593e0f30)


3) Added occupation input field in patientRegister.tsx
![image](https://github.com/coronasafe/care_fe/assets/129517558/c55c546e-d59a-45bb-a587-952a9aecab82)


4) Added to Abha linking 
![image](https://github.com/coronasafe/care_fe/assets/129517558/9e303b75-bbe0-4cba-b9f5-120663eccfc8)


![image](https://github.com/coronasafe/care_fe/assets/129517558/d09f5e3a-e4e2-40a4-a8df-76b818c3942d)


5) Added to data schema in handleSubmit:
![image](https://github.com/coronasafe/care_fe/assets/129517558/db9da4d1-2069-4b0d-96c8-5c9852063b88)


6) Defined in fetchExtResultData in patientReg.tsx itself:
![image](https://github.com/coronasafe/care_fe/assets/129517558/252e8c47-f59c-4c4a-bb3a-4ebe089f98df)


Please have a look and let me know where I'm missing out which is resulting in data not being saved to database.

**Comment by rithviknishad** [comment]
The backend does not have a field called "occupation" in the patient serializer.

Kindly go through the README and have a look at the Care API Docs https://careapi.ohc.network/swagger/

The occupation field is available inside the `meta` field of the patient serializer.

Also, this will require backend changes to be made to support the new options.

<img width="897" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/b257dbdf-48df-4187-835a-712a3122fe51">

**Comment by rithviknishad** [comment]
@aparnacoronasafe should the "any other" option be a free-flow text accepting any input from the user?

**Comment by sagarkori143** [comment]
@rithviknishad can you please explain a bit about what and where I will be in need to implement the changes in backend.

**Comment by sagarkori143** [comment]
@rithviknishad How can I make changes in API response for patient details.

**Comment by vivramkrishna** [comment]
@rithviknishad 

can you please assigne me

**Comment by vivramkrishna** [comment]
@rithviknishad 

in patientregistration table there is no field occupation instead in patientmetainfo
 table occupation is present  but the options are different should i add a new field to patientregistration table or change options in patientmetainfo table
![image](https://github.com/coronasafe/care_fe/assets/101407963/609262db-6811-48f8-b504-536f4a7b6c47)

**Comment by vivramkrishna** [comment]
@rithviknishad 

![image](https://github.com/coronasafe/care_fe/assets/101407963/9a8d2096-008c-4407-84d5-69f82cd2dcee)


in patientmetainfo there no records, should i add occupation field in patientregistration table ?

**Comment by rithviknishad** [comment]
The `meta_info` field may not being used in the current version of `care_fe`. But the backend already has it working. We do have 21 records in `meta_info` table in staging.

You can just update the enum choices

<img width="1747" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/96d509db-a3d1-44e7-9a98-dafcdc8668e2">

**Comment by vivramkrishna** [comment]
@sainak 


when i am trying to load dummy data, I am getting the below error can you please help me to fix this


![image](https://github.com/coronasafe/care_fe/assets/101407963/9e4a0711-fcf7-4160-8952-341a008b7c2b)
![image](https://github.com/coronasafe/care_fe/assets/101407963/5f24be3b-0fd0-4032-aa4c-1c910b86d5e3)

**Comment by vivramkrishna** [comment]
![image](https://github.com/coronasafe/care_fe/assets/101407963/ea076b7a-fca6-48aa-a5a6-013d61bca22e)


should i add video_connect_link field to each user in  dummy data to fix this ?

**Comment by sainak** [comment]
seems like a migration is pending, can you pull the latest changes and restart the containers

**Comment by vivramkrishna** [comment]
No changes have been made, and I have restarted the containers, but It's still showing the same error

**Comment by rithviknishad** [comment]
@konavivekramakrishna wait for the migrations to complete before running `load_dummy_data`

Same issue reported here: https://github.com/coronasafe/care/issues/1833

**Comment by vivramkrishna** [comment]
Thanks, @sainak and  @rithviknishad 

The issue has been fixed now
