### ISSUE TITLE
CNS page card size is inconsistent

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7186]
**Describe the bug**

CNS page card size is inconsistent when the patient name is bigger and it occupies two lines

**To Reproduce**

**Expected behavior**

- [ ] @rithviknishad can you think of a optimal behavior

**Screenshots**

![WhatsApp Image 2024-02-07 at 09 31 31_29a6888e](https://github.com/coronasafe/care_fe/assets/57055998/2a9127d5-6509-49a3-9ba0-781cf0ece076)

**Comment by rithviknishad** [comment]
We can hide the asset name (since it's not very relevant) to a `(i)` info button which when clicked opens a popup that'll show the asset name, middleware and IP address. Also, add a configure button in the popup which will take you to the configure page of that asset.


cc: @nihal467 @aparnacoronasafe

**Comment by thedevildude** [comment]
Can I take up this issue?
@nihal467 @rithviknishad
