### ISSUE TITLE
Issue in finding the value in options tab

### ISSUE THREAD

**Issue by Ashutosh0602** [coronasafe/care_fe#7326]
**Describe the bug**
There was difficulty in finding the suitable user type from the options provided because there was large number of options were available.

<img width="557" alt="Screenshot 2024-03-01 at 12 58 11 AM" src="https://github.com/coronasafe/care_fe/assets/85889617/6a3fbae4-24ac-4d61-ba95-8492ec58b1e4">

**Comment by Ashutosh0602** [comment]
@rithviknishad I have created an issue for this as discussed. 
Please assign me so that I can make PR.

**Comment by nihal467** [comment]
@Ashutosh0602 Unassigning you from this issue due to inactivity. Feel free to reassign yourself if you are still working on it.

**Comment by nihal467** [comment]
marking it discussion required to evaluate its relevance

**Comment by nihal467** [comment]
![image](https://github.com/coronasafe/care_fe/assets/57055998/03e7afc4-ade0-46f8-8366-8f2b39291bc1)

- [ ] The solution to this problem is to change it to an autocomplete field, where users can type and a dropdown will filter based on the input. This is similar to the occupation field in the patient registration form. @aparnacoronasafe , could you comment on your view regarding this change?

**Comment by aparnacoronasafe** [comment]
@nihal467 your suggestion is NOT recommended. When it comes to choosing usertype, the user is trying to look at the list and find the most appropriate type to assign. This cannot be identical to the occupation field where the user already has the occupation in mind and just needs to find it in the list. 

I think this is a non Issue. 

any staff at hospital level will only see 7 options. The long list of options only appear for state level admin users who are only a handful. 

Closing the issue
