### ISSUE TITLE
Error while fetching shifting requests

### ISSUE THREAD

**Issue by khavinshankar** [coronasafe/care_fe#7401]
**Describe the bug**
Getting internal server error while fetching shifting requests, this is happening for only specific statuses `APPROVED`, `DESTINATION APPROVED`, and `COMPLETED` (it's working fine for `PATIENT TO BE PICKED UP`, `TRANSFER IN PROGRESS`).

**To Reproduce**

1. Go to 'Shifting'
2. See error

**Screenshots**
<img width="1467" alt="image" src="https://github.com/coronasafe/care_fe/assets/29787772/29d6f8a9-31d2-4ec5-aa9a-72b6e8e0a40e">

**Additional info**
Here is a sentry log: https://coronasafe-network.sentry.io/share/issue/9af218ddbff649c79ecdcfd0c44f0e86/

**Comment by r-nikhilkumar** [comment]
@khavinshankar, @rithviknishad can you assign this issue to me?

**Comment by hrit2773** [comment]
@khavinshankar can you plz assign me this issue

**Comment by r-nikhilkumar** [comment]
@khavinshankar, @rithviknishad  can you plz assign this issue to me?

**Comment by khavinshankar** [comment]
@hrit2773 this is a high-priority issue, please try to finish it by today

**Comment by hrit2773** [comment]
@khavinshankar issue is from the backend side just tell me to make changes in the backend side I should visit https://github.com/coronasafe/care this repo right? plz clarify

**Comment by khavinshankar** [comment]
@hrit2773 Yes

**Comment by hrit2773** [comment]
@khavinshankar to test the django backend I'm running the docker-compose file but the server is not running on the specified port. what might be the reason?
localstack-1  | 
localstack-1  | LocalStack version: 3.2.1.dev
localstack-1  | LocalStack build date: 2024-03-01
localstack-1  | LocalStack build git hash: db65a08e7
localstack-1  |
localstack-1  | 2024-03-13T17:37:00.787  WARN --- [  MainThread] localstack.deprecations    : EDGE_PORT is deprecated (since 2.0.0) and will be removed in upcoming releases of LocalStack! This configuration will be migrated to GATEWAY_LISTEN
localstack-1  | 2024-03-13T17:37:01.865  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack-1  | 2024-03-13T17:37:01.865  INFO --- [-functhread4] hypercorn.error            : Running on https://0.0.0.0:4566 (CTRL + C to quit)
localstack-1  | 2024-03-13T17:37:02.018  INFO --- [  MainThread] localstack.utils.bootstrap : Execution of "start_runtime_components" took 1229.46ms
localstack-1  | Ready.
localstack-1  | 2024-03-13T17:37:02.043 ERROR --- [  MainThread] localstack.runtime.init    : Error while running script Script(path='/etc/localstack/init/ready.d/bucket-setup.sh', stage=READY, state=ERROR): [Errno 2] No such file or directory: '/etc/localstack/init/ready.d/bucket-setup.sh' can you just tell me how to run the backend locally

**Comment by sainak** [comment]
Taking over as this is a P1 issue
