### ISSUE TITLE
Disable the Bed List of Already occupied Beds

### ISSUE THREAD

**Issue by gayann-au** [coronasafe/care_fe#7569]
Request to Disable the dropdown for already occupied Bed Number in assets-Configurations of HL7 vital Monitors.
Since it creates confusions by showing all the beds on Selecting the beds for the particular HL7 Vital Monitors instead to show only available-Non occupied Beds.
![Screenshot 2024-04-08 170257](https://github.com/coronasafe/care_fe/assets/166367729/0d9eec81-a73a-4196-bfd2-a0d529d22a1d)

**Comment by AnkurPrabhu** [comment]
<img width="551" alt="Screenshot 2024-04-12 at 2 58 40 AM" src="https://github.com/coronasafe/care_fe/assets/85862184/060444bb-cd2f-4c74-a698-34899a2aa3fc">


@rithviknishad in the query object instead of adding `searchAll` we just have to use `unoccupiedOnly` this will solve this issue right ?
let me know if this is what we want ill make the pr for this one

**Comment by r-nikhilkumar** [comment]
@rithviknishad can you please assign this issue to me?

**Comment by rithviknishad** [comment]
@gayann-au By occupied did you mean "occupied by a patient" or "already has another HL7 Monitor linked to that Bed"?

**Comment by gayann-au** [comment]
@rithviknishad Already Has another HL7 Monitor Linked to that Bed

**Comment by nihal467** [comment]
@AnkurPrabhu hide the bed from the dropdown, which is already having a HL7 monitor linked to it
