### ISSUE TITLE
change the "Setting and filter" button behavior in CNS and Live feed page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7600]
**Describe the bug**

when the filters are active in the CNS and live feed page, the button does not show any difference.

**To Reproduce**

1. Go to facility cns page
2. Click on cns page
3. apply any filters

**Expected behavior**

- [ ] change the checkbox on "Hide Monitor without patient" to "Show Monitor without Patient" and bydefault it should be unchecked
- [ ] Neither the Filter by location is in use or show monitor without patient is ticked a , the "Setting and filter" button should be having a primary color button. {Similar behavior of the filter button in the log update filter in the patient consultation page}

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/3633011b-d61e-4839-af2f-e9cf7eeea2a3)

**Comment by tankh99** [comment]
Hi there, I would like to take up this issue. @nihal467 @rithviknishad 

I'd like to clarify a few things
1. Can I assume that instead of 
> "Show Monitor without Patient"

You meant "Show Monitor**s** without patient? Since the existing code already had the plural term

2. What exactly did you mean by
> Neither the Filter by location is in use or show monitor without patient is ticked a

Your sentence got cut off. 

Also, when you mentioned "log update filter", is the bright red "Log Update" button  the one you're referring to, or is it something else? This screenshot was taken in the Patient Details page
<img width="1361" alt="Screenshot 2024-05-01 at 7 46 46 AM" src="https://github.com/coronasafe/care_fe/assets/56617918/9cea4ffd-42ad-4d80-b42e-ff7766b16d83">
