### ISSUE TITLE
Vague Errors in User Profile Page

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#7650]
The following Error is being shown on fresh load of care.ohc.network/user/profile

![image](https://github.com/coronasafe/care_fe/assets/13028584/645aebf1-b7aa-41b3-a116-b6c78d01ecae)

Note: This issue might be specific to Superusers

**Comment by rithviknishad** [comment]
<img width="753" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/81ada15d-f8a0-47fb-87cd-013eb10b7a13">

The issue is the queryset explicitly excludes superuser users. 

<img width="915" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/357cda45-f6b8-4808-9ac5-c0bd8b11ce83">

**Comment by rithviknishad** [comment]
We could instead rely on `/api/v1/users/getcurrentuser` API for this purpose
