### ISSUE TITLE
Modify QR code error notification

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#7708]
**Describe the bug**

- [ ] When we scan a valid QR Code but that asset is not accessible with my user-id privilege, the error throw is "Something went wrong"

**To Reproduce**

1. Go to the asset tab and scan a QR code
2. See error

**Expected behavior**

- [ ] show the proper notification for the above-mentioned scenario 

**Screenshots**

![image](https://github.com/coronasafe/care_fe/assets/57055998/a7531b88-1f41-4fa8-840d-662d0b6d839a)

![image](https://github.com/coronasafe/care_fe/assets/57055998/ccd04f18-4e9a-4de3-a935-a5cd2feb7c56)

**Comment by AnkurPrabhu** [comment]
this will be fixed with my change 
https://github.com/coronasafe/care_fe/pull/7588

**Comment by AshrafMd-1** [comment]
@nihal467 can you assign me this issue

**Comment by AshrafMd-1** [comment]
Actually, the problem here is that when you search for the non authorized qr you get like an error 

<img width="626" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/9ccc0bd2-b025-4fea-bbbb-46bb26d7e356">

that's the reason it shows something went wrong 

but how about  from the backend we display a non-authorized message so we can directly implement it here

**Comment by AshrafMd-1** [comment]
<img width="449" alt="image" src="https://github.com/coronasafe/care_fe/assets/98876115/7b4efea7-8712-4a52-8c76-4c8f02b1421f">


This is how i have handled it

if its okay i will make a PR
