### ISSUE TITLE
Linked skills- to show on patient dashboard for "treating doctor"

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7810]
https://care.coronasafe.in/facility/0c95c7f0-e1d2-4aff-83fa-933cef60d3a8/patient/7e8fc20f-02da-47f7-8c33-f2d8c7e52dd8/consultation/edfe0bd6-0f50-4a4c-8cd0-2d4ad0e9cea1

The patient dashboard shows name of the "treating doctor". After the name of the doctor, show the skills linked to the doctor within "(_)"

**Comment by Sulochan-khadka** [comment]
May you present some UI idea to that... I think since the skills may be large thus, having a dropdown with the heading as Skills would be better.

**Comment by Sulochan-khadka** [comment]
I guess there are two ways in which we can achieve this... 

Like this: (Dropdown)
<img width="1438" alt="Screenshot 2024-05-14 at 3 44 56 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/84015f3c-7d6d-4250-bb94-2d72c2abbb09">


or like this: (SlideOver)
<img width="1438" alt="Screenshot 2024-05-14 at 3 49 37 PM" src="https://github.com/coronasafe/care_fe/assets/122200551/67a3d08b-4137-414c-9b47-0ca8201cc406">

Also let me know if it should have the functionality to unlink the skills or not.

**Comment by Sulochan-khadka** [comment]
@aparnacoronasafe Let me know if I can help you ...

**Comment by Sulochan-khadka** [comment]
Since this is P1, can @rithviknishad @nihal467 comment on this and let me know if I can go ahead and raise a PR?

**Comment by rithviknishad** [comment]
@Sulochan-khadka The UI shown above is not suitable. 

@aparnacoronasafe has already mentioned a good solution on how to show the skills in the UI in the issue comment itself. Just re-explaining...

Show a comma-separated text of skills with a limit of maybe 3. It could be a text in gray color, underlined and cursor pointer. If there are more than 3 skills, show two skills and rest can be shown in a tooltip.


Eg:

```
Treating Doctor:  Dr. Sam Joe  (Skill one, skill two and 3 other skills)
```

Feel free to create a PR since you've already achieved the functionality 😄

**Comment by aparnacoronasafe** [comment]
@Sulochan-khadka please follow the suggestion from @rithviknishad above. 

We do NOT need a button to show linked skills. It must appear on the page itself. So simply adding a text with skills in (..) should suffice. 

When there are multiple skills show them one after the other separated by a comma
