### ISSUE TITLE
Notification not coming up- state admin

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#7912]
When I log in with "state-two" userid (pass: Lilo@123), I am not able to see any notifications in the notification panel. in care.coronasafe.network

**Comment by aparnacoronasafe** [comment]
@nihal467 please test further.

this bug was reported by Sunil. he has state admin account in CARE Sikkim

**Comment by nihal467** [comment]
@aparnacoronasafe 

![image](https://github.com/coronasafe/care_fe/assets/57055998/e65a212f-de5c-4e85-8439-6c59e7ccbf56)

**Issue**: 

The state admin is not receiving any updates related to patient updates because, by default, the user type is not being auto-linked to all facilities in their state.

**Note**:

- If we manually link a facility to the user, they will receive updates. However, auto-linking all facilities in the entire state and receiving updates in notifications may result in the state admin receiving an overwhelming number of unwanted notifications.
- The state admin is not receiving any notices sent to the facilities due to the same reason of not being auto-linked.

**Expected Behavior**

- [ ] all the user notification based on their district should be sent to district admin and similarly state to the state admin ( we need to look into the celery workload this might cause, since a lot of notification will be send to the admin )

**Comment by aparnacoronasafe** [comment]
Expected behaviour is to allow state/district/localbody/ward admins to see notifications from all facilities within the state/district/localbody/ward.

Please check about celery load and see if this is viable

**Comment by aparnacoronasafe** [comment]
PS: I don't think notify feature is working at all. better to test feature and file a separate issue. @nihal467

**Comment by nihal467** [comment]
@aparnacoronasafe as discussed on today's phone call, once you map out notification required for each role type, we can push a proper fix, till that blocking the issue

**Comment by aparnacoronasafe** [comment]
Notification feature needs to be revisited as a whole. Closing the issue. will be filing a diff issue with details
