### ISSUE TITLE
Missing Category for Some Diagnosis

### ISSUE THREAD

**Issue by gigincg** [coronasafe/care_fe#7938]
**Describe the bug**
Missing Category for Some Diagnosis

**To Reproduce**
In a consultation, Mark the Diagnosis as `SD23 Forgetfulness disorder (TM1)`

**Expected behavior**
All Diagnosis should be Categorized

**Screenshots**
![image](https://github.com/coronasafe/care_fe/assets/13028584/24950cbb-adcf-4d8b-bbea-9dcea75a1c48)

**Comment by rithviknishad** [comment]
@aparnacoronasafe 

As per #6231, the chapter for these was marked to be removed. Since the categorisation under text uses this short name shown for showing beside the principal diagnosis, nothing is shown. 

<img width="793" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/5bfef25d-9714-4f1e-a8eb-222b08178556">

<img width="1550" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/c8abac86-6157-4832-89b3-be52e6e96055">

### Possible Solutions

1. Fallback to using the full chapter name (eg: `26 Supplementary Chapter Traditional Medicine Conditions - Module I`)
2. Remove such diagnosis from our ICD 11 table.
3. Disallow making such diagnosis as the principal diagnosis.
4. Have a short name.
5. Have a short name, but still keep it hidden in metabase.
6. Fallback to using the root block.

<img width="824" alt="image" src="https://github.com/coronasafe/care_fe/assets/25143503/92e31f77-621b-4414-8170-7a9b7a158c84">

**Comment by aparnacoronasafe** [comment]
@rithviknishad please go ahead with (2) above. remove all ICD-11s in the chapter from the list itself

**Comment by gigincg** [comment]
I still see Diagnosis without categories @rithviknishad 

![image](https://github.com/coronasafe/care_fe/assets/13028584/cf5bef41-5f99-4700-9cda-5106df40aba5)

**Comment by rithviknishad** [comment]
@sainak Should we consider auto flushing redis on every re-deploy

**Comment by rithviknishad** [comment]
@gigincg This is because redis was not flushed and loaded with new data. However, #2248 should fix it without needing that.

**Comment by gigincg** [comment]
@rithviknishad We'll also need to migrate out data for the options we are blacklisting now

**Comment by rithviknishad** [comment]
@gigincg we could either do:

1. Set such record's as not principal diagnosis and set their verification status as "entered in error" (reversing this migration will not be possible).
2. Soft delete such consultation diagnosis records entirely (reversing this migration is possible).

**Comment by gigincg** [comment]
I think we could leave it as is, as long as the UI clearly shows such  items are "Uncategorized" and don't allow creating further Principal Diagnosis with Uncategorized Options
