### ISSUE TITLE
Make the discharge patient list to have consistent sort by and advance filters

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8198]
**Describe the bug**

Currently, the facility-specific discharge patient list is having correct sort by and advance filters, but this is not consistently kept in the discharge patient list view in the patient list page.

**To Reproduce**

1. login in as a state admin / super admin
2. go to the patient list page
3.  change the view to discharge patients and check the sort by and filters
4. now compare them with the sort by and filters in the facility-specific discharge patient page, which can be accessed from the facility details page
5. See an error

**Expected behavior**

make the sort-by and advance filter in the patient list page similar to the sort-by and advance filter in the facility-specific discharge page.

Note: This change in sort by and advance filter should be done for discharge patient list view, for live patient in the patient tab existing sort by and advance filter should be kept without change

**Screenshots**

![image](https://github.com/user-attachments/assets/aa2768e2-1408-4314-9580-2620d4b581b6)

**Comment by smritidoneria** [comment]
hey, I want to work upon this issue

**Comment by smritidoneria** [comment]
https://github.com/user-attachments/assets/07e5f880-7f56-4289-a9d3-c622d8f95f12

hey @nihal467 , I am not able to reproduce this issue as mentioned. If I am googling to the discharge option, it redirects to select a facilities, and then if I select it, it is redirecting to the facility-specific discharge page, I am not able to see the patient-specific discharge . kindly help me resolve this.

**Comment by nihal467** [comment]
@smritidoneria as mentioned in the issue, you need to login as a super admin or state admin

To check you can use:

User name :State-admin 
Password : Lilo@123

**Comment by smritidoneria** [comment]
okay thanks

**Comment by ahmedobaid23** [comment]
@nihal467 

For the State Admin, the `Advanced Filters` in the `Discharged Patients` list has the following extra filters:

In the `Patient Detail based` section:
  1. `Admitted To (Bed Types)`
  2. `Review Missed`

In the `Geography based` section:
  1. `Facility`
  2. `Facility Type`
  
Other than these two parts, all the filters are same for the State Admin and other users.

I think the `Geography based` extra filters don't need to be removed so that the State Admin can filter the patients according to a specific facility. Right?
Now what about the `Patient Detail based` extra filters?

**Comment by ahmedobaid23** [comment]
@nihal467 

One more thing, the `README.md` does not specify the credentials to login as a State Admin. Shouldn't it be in the `README.md`?

**Comment by nihal467** [comment]
closing this issue as they are not relevant anymore
