### ISSUE TITLE
Remove the Tooltip Message After Cover Image Edit

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8480]
**Describe the bug**

With https://github.com/ohcnetwork/care/pull/2472 we no longer need to show the tooltip as it'll always show the new image.

**To Reproduce**

1. Go to facility tab
2. Click on any facility card
3. upload a cover image to the facility

**Expected behavior**

- Remove the tooltip message should

**Screenshots**

![image](https://github.com/user-attachments/assets/b16e6232-eda1-45af-916a-867f7b75c415)

**Comment by Jacobjeevan** [comment]
@nihal467 Can you assign this issue to me? Thx.

**Comment by rithviknishad** [comment]
@Jacobjeevan 

Let's clear the browser cache using vary header method mentioned in this https://www.fastly.com/blog/clearing-cache-browser. We can perform the cache invalidation once the cover image upload has been completed. This would ensure the latest image is rendered.

cc: @sainak

**Comment by Jacobjeevan** [comment]
@rithviknishad Hmm, since useQuery doesn't support a header parameter, I'd either need to replace it with a fetch outside or modify RequestOptions interface and request function to support header property (preferring the former since it touches less code). Does that sound right, or is there an alternative option?

**Comment by rithviknishad** [comment]
you'll have to use fetch directly to achieve this since the image url is not a defined api route right? useQuery/request requires an API route to be defined, and the image url is not an API route.

**Comment by rithviknishad** [comment]
The additional headers on request options however is useful. Can be done in a separate issue/PR.

**Comment by Jacobjeevan** [comment]
> you'll have to use fetch directly to achieve this since the image url is not a defined api route right? useQuery/request requires an API route to be defined, and the image url is not an API route.

@rithviknishad Oh, I meant moving out the facilityData useQuery to a fetch req (since cover image url is part of that object). Hmm, as for fetching the image url directly, that would require modifications on the backend, right?

**Comment by rithviknishad** [comment]
No, you just need to simply send a fetch request to the signed URL of the image with that vary header, so that browser would invalidate it's cache. Therefore leading to the image component to render the new image as the new image is fetched instead of the old cached one.

Nothing to do with calling any APIs.

**Comment by rithviknishad** [comment]
Read: https://www.fastly.com/blog/clearing-cache-browser

**Comment by Jacobjeevan** [comment]
> No, you just need to simply send a fetch request to the signed URL of the image with that vary header, so that browser would invalidate it's cache. Therefore leading to the image component to render the new image as the new image is fetched instead of the old cached one.
> 
> Nothing to do with calling any APIs.

(1) Couldn't use the fetch + vary method as the HeadersInit type doesn't support it 
> Type '{ "Forced-Revalidate": number; }' is not assignable to type 'HeadersInit | undefined'.

(2) Tried fetch + cache:reload instead. Checking the network tab, it does pull the new version of the image, however I had to append timestamp to have it reflect on page (I tried changing image src directly using getElementById, but that didn't reflect on screen). fetchImage is called on save of the Edit Cover Image Modal/Popup.

It doesn't seem to update the cache though, since the change doesn't persist across page reload.

<img width="482" alt="image" src="https://github.com/user-attachments/assets/04dc6595-6df7-4d62-a083-88212012887b">

https://stackoverflow.com/questions/1077041/refresh-image-with-a-new-one-at-the-same-url/22429796#22429796 mentions few other solutions, including just using timestamp on img src directly, however that would mean storing multiple copies of the same image on cache.

**Comment by rithviknishad** [comment]
I don't see any type errors in `Force-Revalidate: random number as string` method.

Numbers can't be set as header value. However, number as strings can be.

<img width="802" alt="image" src="https://github.com/user-attachments/assets/19886cd1-f4e0-41dd-a961-162c43c9b184">

**Comment by Jacobjeevan** [comment]
> I don't see any type errors in `Force-Revalidate: random number as string` method.
> 
> Numbers can't be set as header value. However, number as strings can be.
> <img alt="image" width="802" src="https://private-user-images.githubusercontent.com/25143503/365390851-19886cd1-f4e0-41dd-a961-162c43c9b184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Njk1MjksIm5iZiI6MTcyNTg2OTIyOSwicGF0aCI6Ii8yNTE0MzUwMy8zNjUzOTA4NTEtMTk4ODZjZDEtZjRlMC00MWRkLWE5NjEtMTYyYzQzYzliMTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDA4MDcwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZmY0NzQ3YzI1NTMzZjdiNGZiYzE2Y2UwZTBkYTkwYWIxMGRiOTI2OGU3MzdhNGI1NmZjZjlmYThlMmUxZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CImqAlWuuVbyy1iAXdbE_6tKLBYqATfrgURDkHlX8Rs">

Ah ok, thanks!

Wouldn't this require `Vary: Forced-Revalidate` on S3? Anyways, I tried with `Forced-Revalidate: 1`. But, I'm getting the same result as (2) in my reply above; new image is pulled by the fetch req in the network tab/dev tools, but only reflected on screen if I append a timestamp to the url. Cache doesn't seem to be updated as the change doesn't persist across page reload.

**Comment by rithviknishad** [comment]
Did you try passing a `key` prop to the img. component?

**Comment by Jacobjeevan** [comment]
> Did you try passing a `key` prop to the img. component?

Never mind, I cleared my browser cache/restarted the dev server and it's working (persists across page reload). Only other issue is the change not reflecting on FacilityCard (if the user navigates thru back button or breadcrumb menu instead of reloading).

**Comment by rithviknishad** [comment]
Hey, could you push the current changes?

**Comment by Jacobjeevan** [comment]
> Hey, could you push the current changes?

Done 👍

**Comment by rithviknishad** [comment]
https://github.com/ohcnetwork/care_fe/pull/8489#issuecomment-2365206712

**Comment by sainak** [comment]
@rithviknishad we still need to remove 

https://github.com/ohcnetwork/care_fe/blob/f62ff79d8d17761500c9ec47b17e4428784d0fd4/src/Components/Facility/FacilityHome.tsx#L60

https://github.com/ohcnetwork/care_fe/blob/f62ff79d8d17761500c9ec47b17e4428784d0fd4/src/Components/Facility/FacilityHome.tsx#L132-L138
