### ISSUE TITLE
Dosage heading is misaligned in the prescription module

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8645]
**Describe the bug**

When we create a PRN prescription with a large note, the dosage heading is misaligned in the normal view

**To Reproduce**

1. Go to patient consultation page
2. Click on medicine and add a medicine (PRN) with a long indicator
3. See error

**Expected behavior**

- [ ] the dosage heading in the prn prescription should be center aligned

**Screenshots**

![image](https://github.com/user-attachments/assets/b0181a97-e8e2-4108-9f17-92d7eb252444)

**Comment by HarshikaAdarsh** [comment]
Hey, is anyone working on this issue? 
If not, I would like to work on it.

**Comment by syedfardeenjeelani** [comment]
hello @HarshikaAdarsh  are you still working on it?

**Comment by ayushpatil2122** [comment]
![image](https://github.com/user-attachments/assets/bf18a62e-7227-4181-bc26-27288d00997d)

But on my machine, everything seems to be fine, even though I added a long note

**Comment by rithviknishad** [comment]
@ayushpatil2122 correction, it's not note, it's indicator. I've updated the issue.

cc: @nihal467

**Comment by siddharthbaleja7** [comment]
@rithviknishad  I would like to work on this issue.Can you please assign this issue to me?

**Comment by NitinPSingh** [comment]
hi @rithviknishad , what if we made it multiline it would solve problem 
![Image](https://github.com/user-attachments/assets/73576ccb-8993-4088-b533-5fd2373a74ac)

or even if truncate it and show the full name on hover, 


if no one is working i would love to contribute

**Comment by Sulochan-khadka** [comment]
I think we can have a scrollable area for indicator, which wont ruin the UI. Also the user can scroll for complete info if needed. Because if we implement the solution formerly stated , the the duration part comes in the scroll which does not seem good.

This is the issue i am talking about:
![Image](https://github.com/user-attachments/assets/8aafc236-fc63-475c-acf8-ecb82fed2750)

The solution i am proposing:
![Image](https://github.com/user-attachments/assets/6350aedc-af87-49e5-b6ed-28ffcd114a9a)

Obviously we can style as required.

Let me know your reviews @rithviknishad @nihal467

**Comment by rithviknishad** [comment]
We could simply either wrap it in newline or elipsis the text beyond a certain max-width. User can anyways see the full information when they click on the row if needed.
