### ISSUE TITLE
Breadcrumbs redirection to patient edit consultation form is not working as expected

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8759]
**Describe the bug**

from the patient consent record page, when we click on the consultation, in the breadcrumbs, we are taken to a new consultation form,not the existing consultation of the patient

**To Reproduce**

1. Go to any active consultation
2. Click on manage patients and click on the consent records
3. view the breadcrumbs on the left side and click on the consultation

**Expected behavior**

- [ ] When we click on the consultation in the breadcrumbs, it should take the user to the patient's existing consultation page

**Screenshots**

![Image](https://github.com/user-attachments/assets/a1df61c6-5cd0-49f8-8e38-37bd6b43161f)

**Comment by noufalrahim** [comment]
@nihal467 can u assign this to me

**Comment by shauryag2002** [comment]
Hi @nihal467 , Can i work on this issue?

**Comment by ahmedobaid23** [comment]
@nihal467 is someone working on this?

**Comment by ahmedobaid23** [comment]
@nihal467 

First of all, these are the breadcrumbs:

![Image](https://github.com/user-attachments/assets/d44acf4f-4906-44f2-8efb-db0d421ad577)

and these are the URIs linked to each of the breadcrumb:

![Image](https://github.com/user-attachments/assets/6666d339-aaf4-408b-a138-0514746520c2)

As you can see, no matter which page you are on, whenever you click on `Consultation` from the breadcrumbs, you will always be redirected to `Create Consultation` page because the URI linked to `Consultation` corresponds to that page in the routing. However if you click on `Admitted on 03:54 PM; 10/12/2023` (which is unclickable from the `Patient Consent Records` page), you will be redirected to the consultation of the patient because of its URI.

Similar is the case for when you click on `Patient` from the breadcrumbs, you will be redirected to `Create Patient` page because the URI linked to `Patient` corresponds to that page in the routing. But when you click on the name of the patient (`Anjali Krishnan` in this case), you will be redirected to her page.

Actually, in many pages like `Patient Dashboard` and `Patient Consent Records` page, the `patientId` and `consultationId` are replaced by patient's name and encounter date respectively as you can see in the picture below:

![Image](https://github.com/user-attachments/assets/07c4fceb-5682-49c2-8079-b8be3ce70ac2)

Also, on every page, the last two crumbs were rendered unclickable (as a span) because of the logic issue. Shouldn't only the last crumb be rendered as unclickable and the rest as a `Link`? In this way, clicking on the `Admitted on 03:54 PM; 10/12/2023` navigates the user to the consultation of the patient.

The solution I have in my mind is to change `Admitted on 03:54 PM; 10/12/2023` back to `consultationId` on all these pages and make it clickable so that clicking it navigates the user back to consultation of the patient.

If you have some other solution, kindly suggest me.

**Comment by shauryag2002** [comment]
@nihal467 ,Working on this issue as the initially assigned person was unable to complete it on time.
