### ISSUE TITLE
Username Validation Warning Prevents Profile Update

### ISSUE THREAD

**Issue by kihan2518B** [coronasafe/care_fe#8811]
**Describe the bug**
When attempting to update the user profile, the system incorrectly triggers a username validation warning, despite the provided username being valid. This prevents users from successfully updating their profile. The issue seems to be related to an incorrect validation check during the profile update process.

**To Reproduce**

1. Go to 'user/profile'
2. Click on 'Edit Profile'
3. Scroll down to 'Update' button
4. Click on 'Update' button
5. See error

**Expected behavior**
The profile should update successfully without any validation errors for the username.

**Screenshots**

![Image](https://github.com/user-attachments/assets/35b0fe3e-d159-450b-9e8d-f2fe654b9b92)

**Comment by NitinPSingh** [comment]
this issue is with username "**dev-districtadmin**", which contains 17 characters , and Validator is configured to accept usernames with a length between 4 and 16 characters, inclusive. Update works well with other username

- username: dev-districtadmin
- password: Coronasafe@123
- role: District Admin

i guess this username was created before adding validator

**Comment by gigincg** [comment]
This is intended behaviour. These are testing usernames that are generated.
