### ISSUE TITLE
Add a cypress test to assign a volunteer to a patient 

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#8913]
**Description**

Add a new cypress test to assign a volunteer to an existing live patient

**General Note**

1. Follow the Page Object Model (POM) approach. : [reference](https://github.com/ohcnetwork/care_fe/blob/develop/cypress/e2e/patient_spec/PatientLogUpdate.cy.ts) 
2. Refer to commands.ts in the Cypress folder to understand existing reusable components.
3. Use proper function names for easier code review.
4.Since there's nothing related to volunteers currently, create a new file named PatientVolunteer.cy.ts under the patient_spec folder.

**Steps to Assign a volunteer**

1. Go to the patient tab
2. click on any live patient card
3. On the patient consultation page, click the Patient Details button in the top-right corner
4. Once the new page loads, scroll down to the Assign New Volunteer button.
5. Assign a new volunteer to the patient.
6. Ensure the newly added volunteer's name is displayed as a banner at the top of the patient details page.

**Make sure to verify the below things**

1. Ensure the normal workflow is functional.
2. Replace the existing volunteer with a new one and verify the banner shows the new volunteer's name.
3. When the volunteer is removed and left blank, verify that the banner is no longer displayed.

**Comment by sidpg123** [comment]
@nihal467 Can I work on this? Please assign it me.

**Comment by sidpg123** [comment]
Hi @nihal467 ,

All tasks mentioned in the issue have been completed as per the requirements:

- Created a new Cypress test under `patient_spec/PatientVolunteer.cy.ts` to assign a volunteer to an existing live patient.
- Since there wasn’t an existing class for the **Patient Details** page, I created one `PatientDetails.ts` and added required functions.
- **Replace Existing Volunteer**: Tested replacing an existing volunteer and verified the updated name appears in the banner.
- **Remove Volunteer**: Verified that removing the volunteer hides the banner as expected.

Additionally, I added an `id` to the banner component for easier targeting.

Please review the changes and let me know if any adjustments are needed.

Thanks!

#### Patient Details Class:
![Image](https://github.com/user-attachments/assets/a4a683fa-39da-401e-91a1-3d74c368c6cf)

#### Test
![Image](https://github.com/user-attachments/assets/3cb07c01-bf33-4887-a188-4190656a4503)

#### Added id to banner: 
![Image](https://github.com/user-attachments/assets/cc967425-0686-40b4-b005-cfc2d52e22ec)

**Comment by JavidSumra** [comment]
Hey @sidpg123 are you working on this issue?

**Comment by sidpg123** [comment]
@JavidSumra yes, i am working on the issue infact work is almost done , i am waiting for @nihal467 confirmation.

**Comment by nihal467** [comment]
@sidpg123 for review purpose, raise the PR

**Comment by nihal467** [comment]
@sidpg123 unassigning you from the issue due to inactivity

**Comment by JavidSumra** [comment]
Hey @nihal467 can you please assign this issue to me?

**Comment by sidpg123** [comment]
@nihal467 Sorry for my inactivity. I have completed the code, but I forgot to raise a PR. If you give me permission, I will raise it immediately.

**Comment by bodhish** [comment]
@sidpg123 do raise a PR.
