### ISSUE TITLE
Fix Auto-Scroll Issue and Total Count Card for Staff Capacity Pagination in facility details page

### ISSUE THREAD

**Issue by nihal467** [coronasafe/care_fe#9122]
**Describe the bug**

Originally report: https://github.com/ohcnetwork/care_fe/pull/9004#issuecomment-2467675505
- [ ] When navigating from page 1 to page 2 in the staff capacity section on the facility details page, the page automatically scrolls to the top.
- [ ] When moving from page 1 to page 2, the total capacity card displays the staff capacity for the current page only, not the entire section.

**To Reproduce**

1. Go to facility details page
2. Add 15+ staff capacity
3. try to move to page no 2

**Expected behavior**

- [ ] Auto-scrolling should stop at the beginning of the staff capacity section, rather than scrolling to the top of the facility details page.
- [ ] The total capacity card should display the total staff capacity for the entire section, not just the current page.

**Screenshots**

![Image](https://github.com/user-attachments/assets/196864f2-56c8-4928-877b-47257bb24dfa)

**Comment by therurouni** [comment]
@nihal467 can i work on this issue?

**Comment by PAVAN507-STAR** [comment]
@Jacobjeevan @nihal467 I found the issue of total count on card ,the problem is the logic only counts from data fetched from current page .I have a doubt/confusion on how to approach ,so is there any api route or any other way to get the entire data of a particular facility?Or do i have to write an api for that?
![Image](https://github.com/user-attachments/assets/3fa61f92-0889-433d-b94b-fb4528d21acd)

**Comment by therurouni** [comment]
@Jacobjeevan @nihal467 I found the issue of total count on card ,the problem is the logic only counts from data fetched from current page .Need a bit of help ,I have a doubt/confusion on how to approach ,so should i  fetch the entire data of all pages at once i.e change limit and offset?Or do i have to write an api for that or is there any other way ?

![Image](https://github.com/user-attachments/assets/3fa61f92-0889-433d-b94b-fb4528d21acd)

![Image](https://github.com/user-attachments/assets/28c10f9e-719d-4eba-8ff1-60d583ac8ef2)

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) [@nihal467](https://github.com/nihal467) I found the issue of total count on card ,the problem is the logic only counts from data fetched from current page .Need a bit of help ,I have a doubt/confusion on how to approach ,so should i fetch the entire data of all pages at once i.e change limit and offset?Or do i have to write an api for that or is there any other way ?
> 
> ![Image](https://github.com/user-attachments/assets/3fa61f92-0889-433d-b94b-fb4528d21acd)
> 
> ![Image](https://github.com/user-attachments/assets/28c10f9e-719d-4eba-8ff1-60d583ac8ef2)

Hmm 🤔 Easiest way would probably be to tweak the api rather than fetching all the results; that would affect pagination unless you want to call the api twice.

In this case, modifying HospitalDoctorViewSet to return the total along with the results should work.

**Comment by therurouni** [comment]
> > [@Jacobjeevan](https://github.com/Jacobjeevan) [@nihal467](https://github.com/nihal467) I found the issue of total count on card ,the problem is the logic only counts from data fetched from current page .Need a bit of help ,I have a doubt/confusion on how to approach ,so should i fetch the entire data of all pages at once i.e change limit and offset?Or do i have to write an api for that or is there any other way ?
> > ![Image](https://github.com/user-attachments/assets/3fa61f92-0889-433d-b94b-fb4528d21acd)
> > ![Image](https://github.com/user-attachments/assets/28c10f9e-719d-4eba-8ff1-60d583ac8ef2)
> 
> Hmm 🤔 Easiest way would probably be to tweak the api rather than fetching all the results; that would affect pagination unless you want to call the api twice.
> 
> In this case, modifying HospitalDoctorViewSet to return the total along with the results should work.

Will give it a try and let u know if it works.Thanks for the help sir.

**Comment by therurouni** [comment]
@Jacobjeevan Hii sir.I'm learning django rn so it make take 2-4 days for me to fix this issue.Hope it's fine.

**Comment by shauryag2002** [comment]
Hi @nihal467, @Jacobjeevan,  

This issue has been stagnant for 2 weeks. Can I take over?  

My approach:  
- [x] Stop auto-scrolling at the staff capacity section instead of the page top.  
- [x] Display total staff capacity for the entire section using the `total_doctor` value in the API response to avoid extra API calls.

https://github.com/user-attachments/assets/698d07f5-f4d9-4658-8008-45d8c6726f1e

**Comment by Jacobjeevan** [comment]
> [@Jacobjeevan](https://github.com/Jacobjeevan) Hii sir.I'm learning django rn so it make take 2-4 days for me to fix this issue.Hope it's fine.

@PAVAN507-STAR any updates here?

**Comment by therurouni** [comment]
@Jacobjeevan I wrote the code to fix the auto scroll and i still have to work on the tweaking the django api part sir.Im actually having some clg exams going on(will be for 1 week ),so i think it's better to assign this to @shauryag2002 .

**Comment by bodhish** [comment]
Resolved inhttps://github.com/ohcnetwork/care_fe/pull/9436
