### ISSUE TITLE
Discharged Patient status showing as "live" 

### ISSUE THREAD

**Issue by samholics** [coronasafe/care_fe#9289]
**Describe the bug**
Discharged patient Status showing as Live for some patients. its happening for the patient having multiple consultations filed. Also it not happening for all the patients

reported by karnataka state official and arike staffs

**To Reproduce**

1. Go to discharged patient on staging website
2. Click on Patient "Raw" or Ritwik Nishad" ( facility - Gayan's Hospital)
3. Go to Patient Details page 

**Expected behavior**
Status should be showing as Discharged for the discharged patients

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JavidSumra** [comment]
Can you please assign this issue to me?

**Comment by Jacobjeevan** [comment]
@JavidSumra Can you open a PR before EOD?

**Comment by JavidSumra** [comment]
Yup I'll do that

**Comment by JavidSumra** [comment]
Hey @Jacobjeevan, I've looked into the issue, and it seems to be with the backend. When fetching the response for a particular discharged patient, the `is_active` flag is incorrectly set to true. Additionally, there are missing fields value such as `"new_discharge_reason"`, `"discharge_notes"`, `"discharge_prescription"`, and `"discharge_prn_prescription"`. To address this, we could pass a parameter in the URL to indicate whether it's the discharged patient page or not.

**Comment by nihal467** [comment]
@samholics The issue arises because the patient is marked as "live" on the patient details page due to their admission to another facility. Since you are accessing the page as  admin,  you can view the details. However, ideally, once a patient is discharged, the patient details page should not be accessible to staff members

This problem occurs because the patient details page is shared across CARE and is not specific to a particular facility.

To address this, we need to define the ideal behavior. Some potential solutions include:

- Removing the "live" status badge from the patient details page.
- Updating the "live" badge to display the name of the current live facility, providing more context.

Or Exploring other approaches to better align the page behavior with the expected workflows after discussing with the users and product teams, meanwhile I am blocking this issue and assigning it to you

**Comment by samholics** [comment]
@aparnacoronasafe need your suggestion on this issue. 
@nihal467 But I do have doubts about the ideal scenario that u mentioned here, if the users /staff are not allowed to access the patient details page when patient is discharged then how they are going to see patients' demographic details, encounters on other facilities, allow or disable transer etc. ??

**Comment by aparnacoronasafe** [comment]
Let's remove the "live" badge from patient details and add it against the specific encounter listed in the patient details page.

**Comment by AdityaJ2305** [comment]
Hey @nihal467 @Jacobjeevan , I’ve created a pull request for it. Could you assign it to me and review it?
