### ISSUE TITLE
The APPROVAL LETTER is not wrapped with the <PrintPreview> component

### ISSUE THREAD

**Issue by modamaan** [coronasafe/care_fe#9324]
**Describe the bug**
The APPROVAL LETTER is not wrapped with the `<PrintPreview>` component

**To Reproduce**

1. Go to 'Resource on sidebar'
2. Click on 'any "all details" button'
3. Click on 'APPROVAL LETTER button'

**Expected behavior**
 Wrap the APPROVAL LETTER with the <PrintPreview> component to provide a better preview experience

**Screenshots**
![Image](https://github.com/user-attachments/assets/f66a9f79-1902-4a03-a3e2-293ea487d300)

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [131.0.6778.109]

**Comment by modamaan** [comment]
@Jacobjeevan  i would like to work on this

**Comment by Rajasimhareddybolla** [comment]
@Jacobjeevan, I’d like to work on this issue.

**Comment by rithviknishad** [comment]
@modamaan assigning to @Rajasimhareddybolla since he has already made a PR. @modamaan Guide him in making the PR right, since you've already worked with PrintPreview component in previous PRs.

**Comment by Rajasimhareddybolla** [comment]
Hi @rithviknishad, @modamaan 

Thanks for your quick feedback!

1. **Duplicate Print Button**: I understand the issue of the duplicate print button due to the existing `PrintPreview` component. To resolve this, I've implemented conditional rendering to hide the redundant print button when the `PrintPreview` component is available.

2. **Button Component**: As requested, I’ve switched to using the primary variant of the `Button` component from the `ui` directory instead of `ButtonV2`.

Here’s the updated outcome:

![Updated Approval Letter Screenshot](https://github.com/user-attachments/assets/00214954-9b2d-4f76-97b5-573a067fba78)

Please let me know if any further changes are required before new PR.

**Comment by nihal467** [comment]
@Rajasimhareddybolla feel free to create a pr for review purpose

**Comment by modamaan** [comment]
@rithviknishad  If @Rajasimhareddybolla is not working on this issue, I would like to take it up
